const songCards = [
    {
        id: 1,
        name: "建炎南渡",
        op: 4,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国未控制开封",
        combat: false,
        effectText: "在两浙路或江南两路免费拥立。宋国获得1国力禁止金国以事件方式在两浙路放置部队。",
        unlock: "【苗刘兵变】",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国未控制开封 效果：在两浙路或江南两路免费拥立。宋国获得1国力禁止金国以事件方式在两浙路放置部队。 解锁：【苗刘兵变】",
        pre: (G, ctx) => !G.song.cities.includes(21),
        event: (G, ctx, arg) => {
            G.song.activeEvents.push('建炎南渡')
        },
    },
    {
        id: 2,
        name: "李纲",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "回合",
        precondition: "第7回合前",
        combat: false,
        effectText: "腐败值减1。本回合余下的时间内，政策倾向视为提升2级的状态（最高为主战3）。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：第7回合前 效果：腐败值减1。本回合余下的时间内，政策倾向视为提升2级的状态（最高为主战3）。",
        pre: (G, ctx) => {
            return G.turnMarker < 7
        },
        event: (G, ctx, arg) => {
            G.song.corruption--;
            G.song.activeEvents.push('李纲')
        },
    },
    {
        id: 3,
        name: "靖康学生运动",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "政策倾向为和议",
        combat: false,
        effectText: "腐败值变为0 ,每因此减少1点腐败值就提升1级政策倾向。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：政策倾向为和议 效果：腐败值变为0 ,每因此减少1点腐败值就提升1级政策倾向。",
        pre: (G, ctx) => getPolicy(G, ctx) < 1,
        event: (G, ctx, arg) => {
            G.song.policy += G.song.corruption;
            G.song.corruption = 0;
        },
    },
    {
        id: 4,
        name: "西军曲端",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "【三年之约】作为事件打出时行动点数减1。每当回合结束阶段时，宋国在陕西六路放置1个步兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：【三年之约】作为事件打出时行动点数减1。每当回合结束阶段时，宋国在陕西六路放置1个步兵。",
        pre: (G, ctx) => !G.jinn.activeEvents.includes("曲端之死"),
        event: (G, ctx, arg) => {
            G.song.activeEvents.push("西军曲端")
        },
    },
    {
        id: 5,
        name: "天下兵马大元帅",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移动1个宋国军团到所在路内或相邻路内1座没有被围困的宋国城市。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移动1个宋国军团到所在路内或相邻路内1座没有被围困的宋国城市。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            // TODO component in player hand
            arg.troop.city = arg.city;
            arg.troop.region = getCityByID(arg.city).region;
        },
    },
    {
        id: 6,
        name: "霹雳炮",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个宋国控制的城市，放置1个霹雳炮。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个宋国控制的城市，放置1个霹雳炮。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            let hasExistingTroop = false;
            for (let troop of G.song.troops) {
                if (troop.city === arg.dst) {
                    hasExistingTroop = true;
                    troop.units[4] += 1;
                }
            }
            if (!hasExistingTroop) {
                G.song.troops.push({
                    units: [0, 0, 0, 0, 1, 0],
                    city: arg.dst,
                })
            }
        },
    },
    {
        id: 7,
        name: "一盆凉水",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "夏季",
        combat: false,
        effectText: "移除斡离不。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：夏季 效果：移除斡离不。",
        pre: (G, ctx) => G.roundMarker === 4 || G.roundMarker === 8,
        event: (G, ctx, arg) => {
            removeGeneral(G, ctx, G.jinn, "斡离不");
        },
    },
    {
        id: 8,
        name: "张邦昌还政",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【靖康之变】发生后",
        combat: false,
        effectText: "金国在开封的军团移动到大同府或大定府，宋国在开封放置1个步兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【靖康之变】发生后 效果：金国在开封的军团移动到大同府或大定府，宋国在开封放置1个步兵。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("靖康之变"),
        event: (G, ctx, arg) => {
            for (let troop of G.jinn.troops) {
                if (troop.city === 21) {
                    troop.city = arg.dst;
                    troop.region = getCityByID(arg.dst).region;
                }
                let troopInKaiFeng = false;
                for (let troop of G.song.troops) {
                    if (troop.city === 21) {
                        troopInKaiFeng = true;
                        troop.units[0]++;
                    }
                }
                if (!troopInKaiFeng) {
                    G.song.troops.push({
                        units: [1, 0, 0, 0, 0, 0],
                        city: 21,
                        region: 43,
                    })
                }
            }
        },
    },
    {
        id: 9,
        name: "耶律大石",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "西辽成为宋国的盟国。若西辽已经是宋国的盟国，消灭金国1个部队。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：西辽成为宋国的盟国。若西辽已经是宋国的盟国，消灭金国1个部队。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            if (G.otherCountries["西辽"].state === 'song') {
                G.eventActionInfo = {
                    type: "kill-X-Units",
                    arg: 1,
                }
                changeStage(G, ctx, 'killUnit');
            } else {
                G.otherCountries["西辽"].state = 'song';
            }
        },
    },
    {
        id: 10,
        name: "李彦仙",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1座被围困的城市放置1个步兵，或者消灭围城军团的1个部队。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1座被围困的城市放置1个步兵，或者消灭围城军团的1个部队。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            changeStage(G, ctx, "LiYanXian");
        },
    },
    {
        id: 11,
        name: "勤王诏令",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国皇帝在场",
        combat: false,
        effectText: "宋国按照补充规则，在宋国控制且殖民难度大于金国殖民能力的城市，放置预备兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国皇帝在场 效果：宋国按照补充规则，在宋国控制且殖民难度大于金国殖民能力的城市，放置预备兵。",
        pre: (G, ctx) => G.song.emperor.exist,
        event: (G, ctx, arg) => G,
    },
    {
        id: 12,
        name: "战车",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宗泽在场",
        combat: true,
        effectText: "战斗牌在平原，宋国每个步兵战斗力加1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宗泽在场 效果：战斗牌在平原，宋国每个步兵战斗力加1。",
        pre: (G, ctx) => G.song.generals["宗泽"].present,
        event: (G, ctx, arg) => G,
    },
    {
        id: 13,
        name: "红巾军",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "金国每控制1个尚未殖民的城市，宋国就在隆德府放置1个步兵〔上限为宋国军事等级〕。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：金国每控制1个尚未殖民的城市，宋国就在隆德府放置1个步兵〔上限为宋国军事等级〕。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 14,
        name: "大理矮脚马",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若大理中立，则征募1个骑兵。若大理是宋国的盟国，则效果翻倍且不受内政等级限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若大理中立，则征募1个骑兵。若大理是宋国的盟国，则效果翻倍且不受内政等级限制。",
        pre: (G, ctx) => G.otherCountries["大理"].state !== 'jinn',
        event: (G, ctx, arg) => {
            if (G.otherCountries["大理"].state === 'song') {
                if (getSongBackupCount(G, ctx,) < G.song.civil) {
                    G.song.reserveBank[2] -= 1;
                    G.song.supplementBank[2] += 1;
                }
            } else {
                let count;
                if (G.song.reserveBank[2] < 2) {
                    count = G.song.reserveBank[2];
                }
                G.song.reserveBank[2] -= count;
                G.song.supplementBank[2] += count;
            }
        },
    },
    {
        id: 15,
        name: "八字军",
        op: 3,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "在河北两路的1个区域，放置2个步兵。【刘錡】伤害加1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在河北两路的1个区域，放置2个步兵。【刘錡】伤害加1。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            G.song.activeEvents.push("八字军");

        },
    },
    {
        id: 16,
        name: "赵榛",
        op: 2,
        country: "宋",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【靖康之变】发生后",
        combat: false,
        effectText: "在1个未完成殖民的金国城市，放置2个步兵，这个城市所在的路结算控制权。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【靖康之变】发生后 效果：在1个未完成殖民的金国城市，放置2个步兵，这个城市所在的路结算控制权。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("靖康之变"),
        event: (G, ctx, arg) => G,
    },
    {
        id: 17,
        name: "金太宗驾崩",
        op: 4,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "第5回合开始之后",
        combat: false,
        effectText: "移除粘罕，选择金国内政等级、军事等级或殖民能力降低1级。",
        unlock: "【完颜昌主和】【天眷新政】",
        block: "【金太宗】",
        ban: "【金太宗】",
        fullDesc: "前置条件：第5回合开始之后 效果：移除粘罕，选择金国内政等级、军事等级或殖民能力降低1级。 解锁：【完颜昌主和】【天眷新政】 禁止：【金太宗】 撤销：【金太宗】",
        pre: (G, ctx) => G.turnMarker > 4,
        event: (G, ctx, arg) => {
            removeGeneral(G, ctx, G.jinn, "粘罕");
            if (arg.target === 'civil' || arg.target === 'military' || arg.target === 'colonization') {
                G.jinn[arg.target]--;
            }

        },
    },
    {
        id: 18,
        name: "废黜伪齐",
        op: 4,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【建立大齐】发生后",
        combat: false,
        effectText: "移除1个齐状态标志物，结算这个路的控制权，消灭2个齐军。若此时齐控制的城市不多于4个，则金国失去齐军征募许可。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【建立大齐】发生后 效果：移除1个齐状态标志物，结算这个路的控制权，消灭2个齐军。若此时齐控制的城市不多于4个，则金国失去齐军征募许可。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("建立大齐"),
        event: (G, ctx, arg) => {

        },
    },
    {
        id: 19,
        name: "岳飞登场",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国军事等级不低于4",
        combat: false,
        effectText: "移除宗泽，在准南两路或荆湖两路放置岳飞。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国军事等级不低于4 效果：移除宗泽，在准南两路或荆湖两路放置岳飞。",
        pre: (G, ctx) => G.song.military >= 4,
        event: (G, ctx, arg) => {
            removeGeneral(G, ctx, G.song, "宗泽");

        },

    },
    {
        id: 20,
        name: "吴玠登场",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在陕西六路或川峡四路内的1个城市放置吴玠。若这座城市没有部队，则放置2个弓兵到该城市",
        unlock: "",
        block: "",
        ban: "【西军曲端】",
        fullDesc: " 效果：在陕西六路或川峡四路内的1个城市放置吴玠。若这座城市没有部队，则放置2个弓兵到该城市 撤销：【西军曲端】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 21,
        name: "韩世忠登场",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国皇帝在场",
        combat: false,
        effectText: "在宋国皇帝所在的区域放置韩世忠。若相邻区域有金国部队，则放置2个步兵到该城市。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国皇帝在场 效果：在宋国皇帝所在的区域放置韩世忠。若相邻区域有金国部队，则放置2个步兵到该城市。",
        pre: (G, ctx) => G.song.emperor.exist,
        event: (G, ctx, arg) => G,
    },
    {
        id: 22,
        name: "无路可退",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国国力不大于7时",
        combat: false,
        effectText: "每当金国失去1点国力，宋国政策倾向提升1级。若事件发生时宋国国力不大于6 ,则立即在3个宋国控制的核心城市各放置1个步兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国国力不大于7时 效果：每当金国失去1点国力，宋国政策倾向提升1级。若事件发生时宋国国力不大于6 ,则立即在3个宋国控制的核心城市各放置1个步兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 23,
        name: "完顔昌主和",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【金太宗驾崩】发生后",
        combat: false,
        effectText: "降低金国1级军事等级。若兀术在场，则放置到预备兵区。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【金太宗驾崩】发生后 效果：降低金国1级军事等级。若兀术在场，则放置到预备兵区。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 24,
        name: "向海上发展",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国内政等级不低于5",
        combat: false,
        effectText: "福建路提供1国力。宋国可以从平江府向高丽进行外交。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国内政等级不低于5 效果：福建路提供1国力。宋国可以从平江府向高丽进行外交。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 25,
        name: "背嵬军",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "征募2个背嵬军。若岳飞在场，则可以在岳飞所在区域，直接放置这2个背嵬军。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：征募2个背嵬军。若岳飞在场，则可以在岳飞所在区域，直接放置这2个背嵬军。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 26,
        name: "伪齐良马",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "齐每控制1个路，宋国就征募1个骑兵（不受内政等级限制〕。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：齐每控制1个路，宋国就征募1个骑兵（不受内政等级限制〕。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 27,
        name: "任用赵鼎 张浚",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "腐败值减1。若腐败值已经为0 ,则提升1级政策倾向。发展阶段时，提供4点发展力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：腐败值减1。若腐败值已经为0 ,则提升1级政策倾向。发展阶段时，提供4点发展力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 28,
        name: "锁江困敌",
        op: 3,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "征募2个战船。若韩世忠在场，则可以在韩世忠所在区域，直接放置这2个战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：征募2个战船。若韩世忠在场，则可以在韩世忠所在区域，直接放置这2个战船。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 29,
        name: "招降",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: true,
        effectText: "战斗牌每消灭或击溃1个签军，就征募1个步兵，不受内政等级限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：战斗牌每消灭或击溃1个签军，就征募1个步兵，不受内政等级限制。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 30,
        name: "浮海逃生",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "当宋国失去皇帝时，可以移除这张牌，移动宋国皇帝到任意宋国控制的城市。",
        unlock: "",
        block: "【搜山检海】",
        ban: "",
        fullDesc: " 效果：当宋国失去皇帝时，可以移除这张牌，移动宋国皇帝到任意宋国控制的城市。 禁止：【搜山检海】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 31,
        name: "改进神臂弓",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国军事等级不低于5",
        combat: false,
        effectText: "宋国弓兵在全部地形战斗力变为2 ,征募消变为2。",
        unlock: "",
        block: "【普及重步兵】",
        ban: "",
        fullDesc: "前置条件：宋国军事等级不低于5 效果：宋国弓兵在全部地形战斗力变为2 ,征募消变为2。 禁止：【普及重步兵】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 32,
        name: "普及重步兵",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国军事等级不低于5",
        combat: false,
        effectText: "宋国步兵耐久度加1。",
        unlock: "",
        block: "【改进神臂弓】",
        ban: "",
        fullDesc: "前置条件：宋国军事等级不低于5 效果：宋国步兵耐久度加1。 禁止：【改进神臂弓】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 33,
        name: "杨沂中",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在宋国皇帝所在的区域放置1个步兵和1个弓兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在宋国皇帝所在的区域放置1个步兵和1个弓兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 34,
        name: "金夏边境冲突",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若西夏是宋国的盟国，则消灭总共2耐久的部队若西夏中立，则消灭总共1耐久的部队。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若西夏是宋国的盟国，则消灭总共2耐久的部队若西夏中立，则消灭总共1耐久的部队。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 35,
        name: "水浒赛",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在泰州地区放置1个战船，在准南两路消灭1个金国部队。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在泰州地区放置1个战船，在准南两路消灭1个金国部队。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 36,
        name: "岳家军",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "岳飞在场",
        combat: true,
        effectText: "战斗牌参战军团中视为增加1个岳飞。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：岳飞在场 效果：战斗牌参战军团中视为增加1个岳飞。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 37,
        name: "驻队矢",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: true,
        effectText: "战斗牌宋国远程部队在远程阶段和交锋阶段优先结算。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：战斗牌宋国远程部队在远程阶段和交锋阶段优先结算。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 38,
        name: "王庶",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【曲端之死】发生后",
        combat: false,
        effectText: "在陕西六路和川峡四路每个宋国控制的城市，各放置1个【步兵】〔上限为宋国军事等级〕。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【曲端之死】发生后 效果：在陕西六路和川峡四路每个宋国控制的城市，各放置1个【步兵】〔上限为宋国军事等级〕。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 39,
        name: "《守城录》",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国军团在城墙时",
        combat: true,
        effectText: "战斗牌金国战斗骰点数减1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国军团在城墙时 效果：战斗牌金国战斗骰点数减1。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 40,
        name: "刘光世",
        op: 2,
        country: "宋",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "腐败值加1。使用这张牌的行动力执行征募和进军，若没有触发任何战斗，则用此牌执行发展。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：腐败值加1。使用这张牌的行动力执行征募和进军，若没有触发任何战斗，则用此牌执行发展。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 41,
        name: "岳帅之来此间震恐",
        op: 4,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "回合",
        precondition: "岳飞在场且宋国军事等级不低于6",
        combat: false,
        effectText: "宋国作战计划替换为【还我河山】。本回合内宋国所有战斗骰点数加1。当岳飞被移除时，此事件被撤销。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：岳飞在场且宋国军事等级不低于6 效果：宋国作战计划替换为【还我河山】。本回合内宋国所有战斗骰点数加1。当岳飞被移除时，此事件被撤销。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 42,
        name: "李显忠登场",
        op: 3,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "西夏向金国方向调整1级。在1个宋国控制的区域放置李显忠和2个骑兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：西夏向金国方向调整1级。在1个宋国控制的区域放置李显忠和2个骑兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 43,
        name: "刘錡",
        op: 3,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "掷骰1次，对1个围城军团造成等于掷骰点数的伤害。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：掷骰1次，对1个围城军团造成等于掷骰点数的伤害。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 44,
        name: "吴璘登场",
        op: 3,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在陕西六路或川峡四路放置吴璘。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在陕西六路或川峡四路放置吴璘。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 45,
        name: "梁兴渡河",
        op: 3,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "岳飞在场",
        combat: false,
        effectText: "降低金国1级殖民能力，用此牌执行发展。发展阶段，此牌提供发展力等于金国占领但没有完成殖民的城市数量。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：岳飞在场 效果：降低金国1级殖民能力，用此牌执行发展。发展阶段，此牌提供发展力等于金国占领但没有完成殖民的城市数量。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 46,
        name: "定都临安",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国皇帝在场",
        combat: false,
        effectText: "移动宋国皇帝到钱塘，用此牌执行派遣。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国皇帝在场 效果：移动宋国皇帝到钱塘，用此牌执行派遣。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 47,
        name: "告老迁乡",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移除银术可。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移除银术可。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => removeGeneral(G, ctx, G.jinn, "银术可"),
    },
    {
        id: 48,
        name: "北谒宋陵",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国控制洛阳",
        combat: false,
        effectText: "用此牌执行发展，宋国摸1张牌。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国控制洛阳 效果：用此牌执行发展，宋国摸1张牌。",
        pre: (G, ctx) => G.song.cities.includes(18),
        event: (G, ctx, arg) => {
            G.song.developCards.push(48);
            drawCardForSong(G, ctx);
        },
    },
    {
        id: 49,
        name: "燕京以南 号令不行",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国控制析津",
        combat: false,
        effectText: "放在宋国完成的作战计划堆最上面。绍兴和议时，宋国额外获得1胜利分数。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国控制析津 效果：放在宋国完成的作战计划堆最上面。绍兴和议时，宋国额外获得1胜利分数。",
        pre: (G, ctx) => G.song.cities.includes(4),
        event: (G, ctx, arg) => G.song.activeEvents.push("燕京以南 号令不行"),
    },
    {
        id: 50,
        name: "李宝",
        op: 2,
        country: "宋",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: true,
        effectText: "战斗牌 在宋国参战军团，放置1个战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：战斗牌 在宋国参战军团，放置1个战船。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
]

const jinnCards = [
    {
        id: 1,
        name: "靖康之变",
        op: 4,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "宋国未控制开封",
        combat: false,
        effectText: "宋国失去1国力。金国获得1国力，并提升1级内政等级。",
        unlock: "【金兵来了】【张邦昌还政】【赵榛】",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国未控制开封 效果：宋国失去1国力。金国获得1国力，并提升1级内政等级。 解锁：【金兵来了】【张邦昌还政】【赵榛】",
        pre: (G, ctx) => !G.song.cities.includes(21),
        event: (G, ctx, arg) => {
            G.jinn.activeEvents.push("靖康之变")
            G.jinn.civil++;
        },
    },
    {
        id: 2,
        name: "折可求献三州",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "金国控制肤施",
        combat: false,
        effectText: "在陕西六路消灭2个部队，并结算路控制权。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：金国控制肤施 效果：在陕西六路消灭2个部队，并结算路控制权。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 3,
        name: "韩昉",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "提升金国1级内政等级或殖民能力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：提升金国1级内政等级或殖民能力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            if (arg === 'civil') G.jinn.civil++;
            if (arg === 'colonization') G.jinn.colonization++;
        },
    },
    {
        id: 4,
        name: "杜充降金",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "消灭1个宋国部队，征募1个签军〔不能消灭皇帝或将领所在区域的部队〕。若【宗泽】不在场，则效果翻倍。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：消灭1个宋国部队，征募1个签军〔不能消灭皇帝或将领所在区域的部队〕。若【宗泽】不在场，则效果翻倍。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 5,
        name: "金太宗",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "在补充阶段开始时可以使用1行动力征募。在发展阶段提供额外1发展力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在补充阶段开始时可以使用1行动力征募。在发展阶段提供额外1发展力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.jinn.activeEvents.push("金太宗"),
    },
    {
        id: 6,
        name: "苗刘兵变",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【建炎南渡】发生后",
        combat: false,
        effectText: "宋国选择以下一项执行：弃掉1张手牌，并移动1个和宋国皇帝相邻的军团到宋国皇帝所在区域；或者宋国失去皇帝。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【建炎南渡】发生后 效果：宋国选择以下一项执行：弃掉1张手牌，并移动1个和宋国皇帝相邻的军团到宋国皇帝所在区域；或者宋国失去皇帝。",
        pre: (G, ctx) => G.song.activeEvents.includes("建炎南渡"),
        event: (G, ctx, arg) => G,
    },
    {
        id: 7,
        name: "渡河！渡河！渡河！",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "第2回合开始之后",
        combat: false,
        effectText: "移除 宗泽",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：第2回合开始之后 效果：移除 宗泽",
        pre: (G, ctx) => G.turnMarker >= 2,
        event: (G, ctx, arg) => removeGeneral(G, ctx, G.song, "宗泽"),
    },
    {
        id: 8,
        name: "追亡逐北",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "移除西辽。",
        unlock: "",
        block: "【耶律大石】",
        ban: "",
        fullDesc: " 效果：移除西辽。 禁止：【耶律大石】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.otherCountries["西辽"].exist = false,
    },
    {
        id: 9,
        name: "济南知府刘豫",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "在历城消灭灭全部宋国部队，放置2个签军。",
        unlock: "【建立大齐】",
        block: "",
        ban: "",
        fullDesc: " 效果：在历城消灭灭全部宋国部队，放置2个签军。 解锁：【建立大齐】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            let t = songTroopInCity(12);
            removeTroop(G, ctx, t);
            if (t.general.length > 0) {
                G.song.pendingGeneralSave = t.general;
                ctx.events.setActivePlayers({others: null})
            }
        },
    },
    {
        id: 10,
        name: "猛安谋克",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "使用3行动力征募。若降低1级殖民能力，则可以使用6行动力征募，且无视内政等级限制。不能征募签军。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：使用3行动力征募。若降低1级殖民能力，则可以使用6行动力征募，且无视内政等级限制。不能征募签军。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            if (arg.colonizeLevelDown) {
                G.opForRecruitAndMarch = 6;
            } else {
                G.opForRecruitAndMarch = 3
            }
            changeStage(G, ctx, 'recruit')
        },
    },
    {
        id: 11,
        name: "辽国旧部",
        op: 3,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "金国每控制西京路、北京路、燕京路或东京路中的1个，就可以使用1行动力征募〔不受内政等级限制",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：金国每控制西京路、北京路、燕京路或东京路中的1个，就可以使用1行动力征募〔不受内政等级限制",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 12,
        name: "六甲神兵",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个被围困的城市发动进攻，在远程阶段城防的作用改为：攻城方增加等于城防的战斗力，守城方减少等于城防的战斗力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个被围困的城市发动进攻，在远程阶段城防的作用改为：攻城方增加等于城防的战斗力，守城方减少等于城防的战斗力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 13,
        name: "金兵来了",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "【靖康之变】发生后且金国军团与宋国皇帝处在相邻区域",
        combat: false,
        effectText: "禁止拥立。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【靖康之变】发生后且金国军团与宋国皇帝处在相邻区域 效果：禁止拥立。",
        pre: (G, ctx) => {
            if (G.jinn.activeEvents.includes("靖康之变") && G.song.emperor.exist) {
                let r = getRegionById(getCityByID(G.song.emperor.city).region);
                let adj = r.adjacentThroughMountainPass.concat(
                    r.waterAdjacent,
                    r.landAdjacent,
                    r.mountainAdjacent
                )
                return adj.some(region => jinnTroopInRegion(region) !== false);
            }
        },
        event: (G, ctx, arg) => G.jinn.activeEvents.push("金兵来了"),

    },
    {
        id: 14,
        name: "西军内斗",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "吴玠或吴璘未参战，且战斗在陕西六路或川峡四路",
        combat: true,
        effectText: "战斗牌宋国战斗骰点数减1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：吴玠或吴璘未参战，且战斗在陕西六路或川峡四路 效果：战斗牌宋国战斗骰点数减1。",
        pre: (G, ctx) => {
            let t = G.combatInfo.song.troop;
            if (t.general.includes("吴玠") || t.general.includes("吴璘")) {
                return false;
            } else {
                // TODO mountain pass
            }
        },
        event: (G, ctx, arg) => G,
    },
    {
        id: 15,
        name: "河面封冻",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "冬季",
        combat: false,
        effectText: "使用1行动力进军，不受河流边界限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：冬季 效果：使用1行动力进军，不受河流边界限制。",
        pre: (G, ctx) => G.turnMarker === 2 || G.roundMarker === 6,
        event: (G, ctx, arg) => {
            G.jinn.activeEvents.push("河面封冻")
            changeStage(G, ctx, "march")
        },
    },
    {
        id: 16,
        name: "掠夺",
        op: 2,
        country: "金",
        era: "早期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "夏季或秋季",
        combat: false,
        effectText: "使用1行动力进军，不受补给限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：夏季或秋季 效果：使用1行动力进军，不受补给限制。",
        pre: (G, ctx) => G.roundMarker === 4 || G.roundMarker === 5 || G.roundMarker === 8 || G.roundMarker === 1,
        event: (G, ctx, arg) => {
            G.jinn.activeEvents.push("掠夺")
            changeStage(G, ctx, "march");
        },
    },
    {
        id: 17,
        name: "张赵之争",
        op: 4,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "放置1个在场的宋国将领到预备兵区或者宋国内政等级降低1级。【莫须有】结算时，金国内政等级视为提升1级的状态。",
        unlock: "【秦桧独相】【淮西军变】",
        block: "【任用赵鼎张浚】",
        ban: "",
        fullDesc: " 效果：放置1个在场的宋国将领到预备兵区或者宋国内政等级降低1级。【莫须有】结算时，金国内政等级视为提升1级的状态。 解锁：【秦桧独相】【淮西军变】 禁止：【任用赵鼎张浚】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 18,
        name: "建立大齐",
        op: 4,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "【济南知府刘豫】发生后",
        combat: false,
        effectText: "在3个金国控制的路，放置齐控制标志，齐控制的城市视为完成了殖民。金国获得齐军征募许可，齐军在任何结算时都同时视为签军。若金国军事等级不小于5 ,签军获得远程属性。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【济南知府刘豫】发生后 效果：在3个金国控制的路，放置齐控制标志，齐控制的城市视为完成了殖民。金国获得齐军征募许可，齐军在任何结算时都同时视为签军。若金国军事等级不小于5 ,签军获得远程属性。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 19,
        name: "兀朮登场",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移除斡离不。在1个金国控制的区域放置兀术。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移除斡离不。在1个金国控制的区域放置兀术。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            removeGeneral(G, ctx, G.jinn, "斡离不")
            // TODO
        },
    },
    {
        id: 20,
        name: "银术可登场",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个金国控制的区域放置银术可。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个金国控制的区域放置银术可。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 21,
        name: "秦桧独相",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "【张赵之争】发生后",
        combat: false,
        effectText: "宋国每回合开始时腐败值加1。【莫须有】结算时，金国内政等级视为再提升1级的状态。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【张赵之争】发生后 效果：宋国每回合开始时腐败值加1。【莫须有】结算时，金国内政等级视为再提升1级的状态。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("张赵之争"),
        event: (G, ctx, arg) => G.jinn.activeEvents.push("秦桧独相"),
    },
    {
        id: 22,
        name: "重点进攻",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移动1个金国军团到所在路内或相邻路内1座没有被围困的金国城市。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移动1个金国军团到所在路内或相邻路内1座没有被围困的金国城市。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 23,
        name: "三年之约",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "夏季或秋季",
        combat: false,
        effectText: "在陕西六路，使用本卡牌的行动力对任意没有宋国将领的军团执行进军。移除娄室。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：夏季或秋季 效果：在陕西六路，使用本卡牌的行动力对任意没有宋国将领的军团执行进军。移除娄室。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 24,
        name: "淮西军变",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【张赵之争】发生后",
        combat: false,
        effectText: "在准南两路，消灭2个部队。征募2个步兵和1个战船（不受内政等级限制〕。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【张赵之争】发生后 效果：在准南两路，消灭2个部队。征募2个步兵和1个战船（不受内政等级限制〕。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("张赵之争"),
        event: (G, ctx, arg) => G,
    },
    {
        id: 25,
        name: "烽火扬州路",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "金国控制杨州地区",
        combat: false,
        effectText: "与另1张牌一起打出，行动点数合并计算。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：金国控制杨州地区 效果：与另1张牌一起打出，行动点数合并计算。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 26,
        name: "搜山检海",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "宋国皇帝被围困",
        combat: false,
        effectText: "宋国失去皇帝。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：宋国皇帝被围困 效果：宋国失去皇帝。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            G.song.emperor.exist = false;
            if (G.song.policy > -3) G.song.policy--;
        },
    },
    {
        id: 27,
        name: "孤注一掷",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "齐只控制1个路",
        combat: false,
        effectText: "降低1级殖民能力，在所有齐控制的城市，各放置1个签军和1个拐子马。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：齐只控制1个路 效果：降低1级殖民能力，在所有齐控制的城市，各放置1个签军和1个拐子马。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 28,
        name: "唃厮啰入侵",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若吐蕃中立，在川峡四路，放置1个步兵；若吐蕃是金国的盟国，则效果翻倍。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若吐蕃中立，在川峡四路，放置1个步兵；若吐蕃是金国的盟国，则效果翻倍。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 29,
        name: "天眷新政",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "【金太宗驾崩】发生后",
        combat: false,
        effectText: "弃掉数是最多等于内政等级的手牌，然后从金国牌库摸取相等数畺的牌。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：【金太宗驾崩】发生后 效果：弃掉数是最多等于内政等级的手牌，然后从金国牌库摸取相等数畺的牌。",
        pre: (G, ctx) => G.jinn.activeEvents.includes("金太宗驾崩"),
        event: (G, ctx, arg) => G,
    },
    {
        id: 30,
        name: "不见来使",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "无",
        combat: false,
        effectText: "禁止宋国对高丽执行外交。若高丽是金国的盟国，则在发展阶段额外提供1发展力。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：禁止宋国对高丽执行外交。若高丽是金国的盟国，则在发展阶段额外提供1发展力。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.jinn.activeEvents.push("不见来使"),
    },
    {
        id: 31,
        name: "曲端之死",
        op: 3,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "金国控制河东路或陕西六路",
        combat: false,
        effectText: "在陕西六路，消灭2个部队。",
        unlock: "",
        block: "【西军曲端】",
        ban: "【西军曲端】",
        fullDesc: "前置条件：金国控制河东路或陕西六路 效果：在陕西六路，消灭2个部队。 禁止：【西军曲端】 撤销：【西军曲端】",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.jinn.activeEvents.push("曲端之死"),
    },
    {
        id: 32,
        name: "火攻",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "兀术在场",
        combat: true,
        effectText: "战斗牌消灭1个参战的宋国战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：兀术在场 效果：战斗牌消灭1个参战的宋国战船。",
        pre: (G, ctx) => G.jinn.generals["兀术"].present,
        event: (G, ctx, arg) => G,
    },
    {
        id: 33,
        name: "江淮流宼",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个宋国控制的路内，没有宋国军团的区域，放置1个签军和1个战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个宋国控制的路内，没有宋国军团的区域，放置1个签军和1个战船。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 34,
        name: "胡服乡兵",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "有签军参战",
        combat: true,
        effectText: "战斗牌消灭1个参战的宋国步兵或弓兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：有签军参战 效果：战斗牌消灭1个参战的宋国步兵或弓兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 35,
        name: "李成",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个有签军的军团内，放置2个步兵。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个有签军的军团内，放置2个步兵。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 36,
        name: "徐州冶铁",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "内政等级不低于5且控制京东两路",
        combat: false,
        effectText: "铁浮屠征募消耗变为1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：内政等级不低于5且控制京东两路 效果：铁浮屠征募消耗变为1。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            G.jinn.recruitCost[2] = 1;
            G.jinn.activeEvents.push("徐州冶铁")
        },
    },
    {
        id: 37,
        name: "孔彦舟",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个有签军的军团内，放置1个战船。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个有签军的军团内，放置1个战船。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 38,
        name: "杀马为粮",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "替换1个金国骑行部队为步兵，这个步兵所在的军团立即进军，不受补给限制。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：替换1个金国骑行部队为步兵，这个步兵所在的军团立即进军，不受补给限制。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 39,
        name: "徽宗病逝",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若【靖康之变】已经发生，免费和议。若【靖康之变】没有发生，宋国随机弃掉1张手牌",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若【靖康之变】已经发生，免费和议。若【靖康之变】没有发生，宋国随机弃掉1张手牌",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 40,
        name: "南人归南 北人归北",
        op: 2,
        country: "金",
        era: "中期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "用此牌发展，提供发展力等于实时殖民能力的2倍",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：用此牌发展，提供发展力等于实时殖民能力的2倍",
        pre: (G, ctx) => false,
        event: (G, ctx, arg) => G,
    },
    {
        id: 41,
        name: "莫須有",
        op: 4,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "金国内政等级不低于7",
        combat: false,
        effectText: "降低2级政策倾向，消灭宋国总共4个部队。若此时政策倾向为和议，则移除岳飞。否则，放置岳飞到预备兵区。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：金国内政等级不低于7 效果：降低2级政策倾向，消灭宋国总共4个部队。若此时政策倾向为和议，则移除岳飞。否则，放置岳飞到预备兵区。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 42,
        name: "奔睹登场",
        op: 3,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "在1个金国控制的区域放置奔睹。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：在1个金国控制的区域放置奔睹。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 43,
        name: "天眷政变",
        op: 3,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "金国军事等级不低于5",
        combat: false,
        effectText: "提升金国1级军事等级，本回合作战计划替换为【吴山立马】。",
        unlock: "",
        block: "【完颜昌主和】",
        ban: "",
        fullDesc: "前置条件：金国军事等级不低于5 效果：提升金国1级军事等级，本回合作战计划替换为【吴山立马】。 禁止：【完颜昌主和】",
        pre: (G, ctx) => G.jinn.military >= 5,
        event: (G, ctx, arg) => G,
    },
    {
        id: 44,
        name: "十二道金牌",
        op: 3,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "政策倾向为和议",
        combat: false,
        effectText: "使用该卡牌的行动点数，对宋国军团执行进军，不能触发战斗，不能移动到缺乏补给的区域。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：政策倾向为和议 效果：使用该卡牌的行动点数，对宋国军团执行进军，不能触发战斗，不能移动到缺乏的区域。",
        pre: (G, ctx) => getPolicy(G, ctx) < 0,
        event: (G, ctx, arg) => G,
    },
    {
        id: 45,
        name: "败盟南下",
        op: 3,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "降低1级政策倾向，使用这张牌的行动力执行征募和进军。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：降低1级政策倾向，使用这张牌的行动力执行征募和进军。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            if (G.song.policy > -3) G.song.policy--;
            G.opForRecruitAndMarch = 3;
            changeStage(G, ctx, 'recruitOrMarch')
        },
    },
    {
        id: 46,
        name: "解除兵权",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "持续",
        precondition: "政策倾向为和议",
        combat: false,
        effectText: "若宋国皇帝在场，则将韩世忠移动到皇帝所在区域，韩世忠之后只能随宋国皇帝移动。否则，移除韩世忠。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：政策倾向为和议 效果：若宋国皇帝在场，则将韩世忠移动到皇帝所在区域，韩世忠之后只能随宋国皇帝移动。否则，移除韩世忠。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G,
    },
    {
        id: 47,
        name: "臣构言",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "若政策倾向为和议，提升1级殖民能力。若政策倾向为主战或中立，降低1级政策倾向。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：若政策倾向为和议，提升1级殖民能力。若政策倾向为主战或中立，降低1级政策倾向。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => {
            if (getPolicy(G, ctx,) < 0) {
                G.jinn.colonization++;
            } else {
                if (G.song.policy > -3) G.song.policy--;
            }
        },
    },
    {
        id: 48,
        name: "吴玠病逝",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "移除吴玠",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：移除吴玠",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => removeGeneral(G, ctx, G.jinn, "吴玠"),
    },
    {
        id: 49,
        name: "钱眼将军张俊",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "无",
        combat: false,
        effectText: "宋国腐败值加1。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: " 效果：宋国腐败值加1。",
        pre: (G, ctx) => true,
        event: (G, ctx, arg) => G.song.corruption++,
    },
    {
        id: 50,
        name: "疑兵",
        op: 2,
        country: "金",
        era: "后期",
        removeAfterEvent: false,
        eventProperty: "立即",
        precondition: "奔睹在场，且金国守城",
        combat: true,
        effectText: "战斗牌先于任何战斗卡结算，宋国军团立即撤退，全部战斗结算结束。",
        unlock: "",
        block: "",
        ban: "",
        fullDesc: "前置条件：奔睹在场，且金国守城 效果：战斗牌先于任何战斗卡结算，宋国军团立即撤退，全部战斗结算结束。",
        pre: (G, ctx) => G.jinn.generals["奔睹"].present && G.combatInfo.isSiege && G.combatInfo.song.isAttacker,
        event: (G, ctx, arg) => G,
    },
]
let t;
const all = [...songCards, ...jinnCards];
all.forEach(
    e => {
        let d;
        let l;
        if (e.country === "宋") {
            d = `SongBasicCardID.S${e.id.toString().padStart(2, '0')}`;
            l = `[${d}]:{id:${d},name:"${e.name}",op:${e.op},country:Country.SONG,`;
        } else {

            d = `JinnBasicCardID.J${e.id.toString().padStart(2, '0')}`;
            l = `[${d}]:{id:${d},name:"${e.name}",op:${e.op},country:Country.JINN,`;
        }
        switch (e.era) {
            case "早期":
                l += `era:IEra.E,`;
                break;
            case "中期":
                l += `era:IEra.M,`;
                break;
            case "后期":
                l += `era:IEra.L,`;
                break;
        }
        l += `remove:${e.removeAfterEvent},`;
        if (e.precondition === "无") {
            l += `precondition:null,`;
        } else {
            l += `precondition:"${e.precondition}",`;
        }
        if (e.ban === "") {
            l += `ban:null,`;

        } else {
            l += `ban:"${e.ban}",`;
        }
        if (e.block === "") {
            l += `block:null,`;

        } else {
            l += `block:"${e.block}",`;
        }
        if (e.unlock === "") {
            l += `unlock:null,`;

        } else {
            l += `unlock:"${e.unlock}",`;
        }
        if (e.eventProperty === "立即") {
            l += `duration:EventDuration.INSTANT,`;
        } else {
            l += `duration:EventDuration.CONTINUOUS,`;
        }
        l += `combat:${e.combat},`;
        l += `effectText:"${e.effectText}",`;
        l += 'pre:(G: SongJinnGame, ctx:Ctx)=>true,event:(G: SongJinnGame, ctx:Ctx)=>G},';
        console.log(l);
        t += l;
    }
)

const plans = [
    {
        id: 0, name: "",
        desc: "",
        effect: (G, ctx, arg) => G,
        level: 0,
        provinces: [],
        vp: 0,
    }, {
        id: 1,
        name: "早期京畿路",
        desc: "核心/目标：开封   其他城市：无   首次完成/奖励选取奖励：下一个摸牌阶段，通过检索获得1张手牌，然后弃掉1张手牌",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 2,
        name: "早期陕西六路",
        desc: "核心/目标：长安   其他城市：天兴 肤施   首次完成/奖励选取奖励：提高【军事等级】1级",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 3,
        name: "早期京西两路",
        desc: "核心/目标：襄阳   其他城市：洛阳宛丘   首次完成/奖励选取奖励：提高【政策】/【殖民】1级",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 4,
        name: "早期京东两路",
        desc: "核心/目标：宋城   其他城市：历城须城   首次完成/奖励选取奖励：调整1个其他国家【外交】状态1级",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 5,
        name: "早期淮南两路",
        desc: "核心/目标：江都   其他城市：下蔡   首次完成/奖励选取奖励：提高【内政等级】1级",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 6,
        name: "早期河东路",
        desc: "核心/目标：阳曲   其他城市：临汾上党   首次完成/奖励选取奖励：消灭总共2耐久度的部队",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 7,
        name: "中期京畿路",
        desc: "核心/目标：开封   其他城市：无   首次完成/奖励选取奖励：下一个摸牌阶段，通过检索获得1张手牌，然后弃掉1张手牌",
        effect: (G, ctx, arg) => G,
        level: 3,
        provinces: [],
        vp: 2,
    },
    {
        id: 8,
        name: "中期陕西六路",
        desc: "核心/目标：长安   其他城市：   首次完成/奖励选取奖励：提高【军事等级】1级",
        effect: (G, ctx, arg) => G,
        level: 3,
        provinces: [],
        vp: 2,
    },
    {
        id: 9,
        name: "中期淮南两路",
        desc: "核心/目标：江都   其他城市：下蔡   首次完成/奖励选取奖励：提高【内政等级】1级",
        effect: (G, ctx, arg) => G,
        level: 3,
        provinces: [],
        vp: 2,
    },
    {
        id: 10,
        name: "中期京西两路",
        desc: "核心/目标：襄阳   其他城市：洛阳宛丘   首次完成/奖励选取奖励：提高【政策】，【殖民】1级",
        effect: (G, ctx, arg) => G,
        level: 3,
        provinces: [],
        vp: 2,
    },
    {
        id: 11,
        name: "中期荆湖两路",
        desc: "核心/目标：江陵   其他城市：长沙安陆   首次完成/奖励选取奖励：提供4点【发展力】",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 12,
        name: "中期川峡四路",
        desc: "核心/目标：成都   其他城市：南郑 郪县   首次完成/奖励选取奖励：摸1张牌",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 13,
        name: "中期京东两路",
        desc: "核心/目标：宋城   其他城市：历城须城   首次完成/奖励选取奖励：调整1个其他国家【外交】状态1级",
        effect: (G, ctx, arg) => G,
        level: 3,
        provinces: [],
        vp: 2,
    },
    {
        id: 14,
        name: "中期江西两路",
        desc: "核心/目标：江宁   其他城市：南昌   首次完成/奖励选取奖励：提高【政策】/【殖民】1级",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 15,
        name: "中期河北两路",
        desc: "核心/目标：元城   其他城市：真定 安喜 河间   首次完成/奖励选取奖励：在【元城】放置1个【拐子马】/【背嵬军】",
        effect: (G, ctx, arg) => G,
        level: 2,
        provinces: [],
        vp: 1,
    },
    {
        id: 16,
        name: "中期川陕战区",
        desc: "核心/目标：长安   其他城市：天兴 肤施 南郑 郪县   首次完成/奖励选取奖励：将1个在场的【将领】移出游戏",
        effect: (G, ctx, arg) => G,
        level: 4,
        provinces: [],
        vp: 4,
    },
    {
        id: 17,
        name: "中期荆襄战区",
        desc: "核心/目标：襄阳开封   其他城市：洛阳宛丘   首次完成/奖励选取奖励：将1个已完成的【作战计划】移出游戏",
        effect: (G, ctx, arg) => G,
        level: 4,
        provinces: [],
        vp: 4,
    },
    {
        id: 18,
        name: "中期两淮战区",
        desc: "核心/目标：江都宋城   其他城市：历城须城下蔡   首次完成/奖励选取奖励：将1个其他国家移出游戏",
        effect: (G, ctx, arg) => G,
        level: 4,
        provinces: [],
        vp: 4,
    },
    {
        id: 19,
        name: "后期京畿路",
        desc: "核心/目标：开封   其他城市：无   首次完成/奖励选取奖励：无",
        effect: (G, ctx, arg) => G,
        level: 4,
        provinces: [],
        vp: 3,
    },
    {
        id: 20,
        name: "后期陕西六路",
        desc: "核心/目标：长安   其他城市：   首次完成/奖励选取奖励：无",
        effect: (G, ctx, arg) => G,
        level: 4,
        provinces: [],
        vp: 3,
    },
    {
        id: 21,
        name: "后期淮南两路",
        desc: "核心/目标：江都   其他城市：下蔡   首次完成/奖励选取奖励：下回合可以选取2张【作战计划】",
        effect: (G, ctx, arg) => G,
        level: 3,
        provinces: [],
        vp: 2,
    },
    {
        id: 22,
        name: "后期京西两路",
        desc: "核心/目标：襄阳   其他城市：洛阳宛丘   首次完成/奖励选取奖励：无",
        effect: (G, ctx, arg) => G,
        level: 4,
        provinces: [],
        vp: 3,
    },
    {
        id: 23,
        name: "还我河山",
        desc: "核心/目标：长安 宋城 元城 开封    其他城市：肤施天兴须城历城河间安喜真定   首次完成/奖励选取奖励：自动获胜；若未完成，当【绍兴和议】时，每座计划内的城市1分",
        effect: (G, ctx, arg) => G,
        level: 5,
        provinces: [],
        vp: 0,
    },
    {
        id: 24,
        name: "吴山立马",
        desc: "核心/目标：江宁襄阳江都开封   其他城市：下蔡南昌洛阳宛丘   首次完成/奖励选取奖励：自动获胜；若未完成，当【绍兴和议】时，每座计划内的城市1分",
        effect: (G, ctx, arg) => G,
        level: 5,
        provinces: [],
        vp: 0,
    },
]

plans.forEach(e => {
        let t = `[PlanID.J${e.id.toString().padStart(2, '0')}]:${JSON.stringify(e)}`;
        t = t.slice(0, -1);
        t += ',effect: (G: SongJinnGame, ctx: Ctx) => {}},';
        console.log(t);
    }
)