const regions = [{
    id: 1,
    name: "云内洲地区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [2, 3],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 1,
    cityID: 0,
    x: 167,
    y: 22
}, {
    id: 2,
    name: "大同府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [1, 3, 4, 5,],
    waterAdjacent: [],
    adjacentThroughMountainPass: [7,],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 1,
    cityID: 1,
    x: 190,
    y: 35
}, {
    id: 3,
    name: "武朔两州",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [1, 2, 4, 9, 10],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 1,
    cityID: 0,
    x: 167,
    y: 40
}, {
    id: 4,
    name: "应蔚两州",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [2, 3, 7, 10, 13, 14],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 1,
    cityID: 0,
    x: 213,
    y: 49
}, {
    id: 5,
    name: "大定府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [2, 6, 7, 8],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 2,
    cityID: 2,
    x: 251,
    y: 27
}, {
    id: 6,
    name: "辽阳府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [2,],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 3,
    cityID: 3,
    x: 317,
    y: 49
}, {
    id: 7,
    name: "析津府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [4, 5, 8, 14, 15],
    waterAdjacent: [16,],
    adjacentThroughMountainPass: [2,],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 4,
    cityID: 4,
    x: 234,
    y: 51
}, {
    id: 8,
    name: "平州",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [5, 7],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 4,
    cityID: 0,
    x: 247,
    y: 54
}, {
    id: 9,
    name: "山西高原",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [3, 10, 11],
    waterAdjacent: [32,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 5,
    cityID: 0,
    x: 174,
    y: 77
}, {
    id: 10,
    name: "太原府",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [3, 4, 9, 11, 12, 13, 17],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 5,
    cityID: 5,
    x: 189,
    y: 81
}, {
    id: 11,
    name: "平阳府",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [9, 10, 12, 36],
    waterAdjacent: [32,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 5,
    cityID: 6,
    x: 176,
    y: 94
}, {
    id: 12,
    name: "隆德府",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [10, 11, 17, 19],
    waterAdjacent: [37,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 5,
    cityID: 7,
    x: 198,
    y: 93
}, {
    id: 13,
    name: "真定府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [4, 10, 14, 17],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 6,
    cityID: 8,
    x: 213,
    y: 67
}, {
    id: 14,
    name: "中山府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [4, 7, 13, 15, 17],
    waterAdjacent: [16,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 6,
    cityID: 9,
    x: 227,
    y: 62
}, {
    id: 15,
    name: "河间府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [7, 14],
    waterAdjacent: [16,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 6,
    cityID: 10,
    x: 241,
    y: 72
}, {
    id: 16,
    name: "沧州",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [18,],
    waterAdjacent: [14, 15, 17, 21,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 6,
    cityID: 0,
    x: 248,
    y: 82
}, {
    id: 17,
    name: "庆源府和信德府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [10, 13, 14, 12, 19],
    waterAdjacent: [18,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 6,
    cityID: 0,
    x: 221,
    y: 85
}, {
    id: 18,
    name: "大名府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [16,],
    waterAdjacent: [17, 20, 21, 25],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 6,
    cityID: 11,
    x: 236,
    y: 89
}, {
    id: 19,
    name: "卫州地区",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [12, 17],
    waterAdjacent: [37, 43, 20],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 6,
    cityID: 0,
    x: 217,
    y: 106
}, {
    id: 20,
    name: "开德府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [24, 25, 43],
    waterAdjacent: [18, 19],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 6,
    cityID: 0,
    x: 233,
    y: 100
}, {
    id: 21,
    name: "济南府",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [25, 26, 27],
    waterAdjacent: [16, 18],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 7,
    cityID: 12,
    x: 260,
    y: 89
}, {
    id: 22,
    name: "潍密两州",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [21, 27, 23, 44],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 7,
    cityID: 0,
    x: 283,
    y: 106
}, {
    id: 23,
    name: "登州",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [23,],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 7,
    cityID: 0,
    x: 300,
    y: 82
}, {
    id: 24,
    name: "兴仁府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [20, 25, 28, 43],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 7,
    cityID: 0,
    x: 237,
    y: 117
}, {
    id: 25,
    name: "东平府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [20, 21, 24, 26, 28],
    waterAdjacent: [18,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 7,
    cityID: 13,
    x: 245,
    y: 113
}, {
    id: 26,
    name: "裘庆府",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [21, 25, 27, 28],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 7,
    cityID: 0,
    x: 257,
    y: 114
}, {
    id: 27,
    name: "沂州",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [21, 22, 26, 28, 44, 45],
    waterAdjacent: [46,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 7,
    cityID: 0,
    x: 266,
    y: 111
}, {
    id: 28,
    name: "应天府",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [24, 25, 26, 27, 43, 45],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 7,
    cityID: 14,
    x: 248,
    y: 131
}, {
    id: 29,
    name: "熙河路地区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [30, 33],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 8,
    cityID: 0,
    x: 91,
    y: 122
}, {
    id: 30,
    name: "泾原路地区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [29, 31, 33],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 8,
    cityID: 0,
    x: 106,
    y: 100
}, {
    id: 31,
    name: "环庆路地区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [30, 32, 34],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 8,
    cityID: 0,
    x: 136,
    y: 106
}, {
    id: 32,
    name: "延安府",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [31, 34],
    waterAdjacent: [9, 11],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 8,
    cityID: 15,
    x: 153,
    y: 85
}, {
    id: 33,
    name: "凤翔府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [29, 30, 31, 34, 35],
    waterAdjacent: [],
    adjacentThroughMountainPass: [52,],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 8,
    cityID: 16,
    x: 125,
    y: 134
}, {
    id: 34,
    name: "关中平原",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [30, 31, 32, 33],
    waterAdjacent: [11, 35, 36],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 8,
    cityID: 0,
    x: 162,
    y: 124
}, {
    id: 35,
    name: "河中府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [11,],
    waterAdjacent: [34, 35, 37],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 8,
    cityID: 0,
    x: 182,
    y: 126
}, {
    id: 36,
    name: "京兆府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [33,],
    waterAdjacent: [34, 35],
    adjacentThroughMountainPass: [37, 40],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 8,
    cityID: 17,
    x: 164,
    y: 144
}, {
    id: 37,
    name: "河南府",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [38, 40, 43],
    waterAdjacent: [11, 12, 19, 35],
    adjacentThroughMountainPass: [36,],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 9,
    cityID: 18,
    x: 202,
    y: 128
}, {
    id: 38,
    name: "颖昌府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [37, 40, 41, 43],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 9,
    cityID: 0,
    x: 210,
    y: 141
}, {
    id: 39,
    name: "秦巴山区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [40, 52],
    waterAdjacent: [42,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 9,
    cityID: 0,
    x: 168,
    y: 164
}, {
    id: 40,
    name: "邓州",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [37, 38, 39, 41, 42],
    waterAdjacent: [],
    adjacentThroughMountainPass: [36,],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 9,
    cityID: 0,
    x: 199,
    y: 156
}, {
    id: 41,
    name: "淮宁",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [38, 40, 42, 43, 45],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 9,
    cityID: 19,
    x: 231,
    y: 151
}, {
    id: 42,
    name: "襄阳",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [39, 40, 41, 61],
    waterAdjacent: [39, 59, 60, 61],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 9,
    cityID: 20,
    x: 202,
    y: 169
}, {
    id: 43,
    name: "开封府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [20, 24, 28, 37, 38, 41, 45],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 10,
    cityID: 21,
    x: 225,
    y: 132
}, {
    id: 44,
    name: "海州",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [22, 27, 46],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 11,
    cityID: 0,
    x: 281,
    y: 137
}, {
    id: 45,
    name: "宿毫两州",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [27, 28, 41, 43],
    waterAdjacent: [48,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 11,
    cityID: 0,
    x: 255,
    y: 148
}, {
    id: 46,
    name: "扬州地区",
    terrainType: "TerrainType.SWAMP",
    landAdjacent: [44, 48, 50],
    waterAdjacent: [27, 45, 66, 72],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 11,
    cityID: 22,
    x: 280,
    y: 156
}, {
    id: 47,
    name: "泰州地区",
    terrainType: "TerrainType.SWAMP",
    landAdjacent: [46,],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 11,
    cityID: 0,
    x: 298,
    y: 162
}, {
    id: 48,
    name: "寿春府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [46, 49, 50],
    waterAdjacent: [41, 45],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 11,
    cityID: 23,
    x: 247,
    y: 172
}, {
    id: 49,
    name: "江淮丘陵",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [48, 50, 61],
    waterAdjacent: [41, 65, 68, 69],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 11,
    cityID: 0,
    x: 233,
    y: 186
}, {
    id: 50,
    name: "巢湖平原",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [46, 48, 49],
    waterAdjacent: [66, 67, 69],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 11,
    cityID: 0,
    x: 256,
    y: 185
}, {
    id: 51,
    name: "利州地区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [52,],
    waterAdjacent: [],
    adjacentThroughMountainPass: [54, 55,],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 12,
    cityID: 0,
    x: 112,
    y: 166
}, {
    id: 52,
    name: "兴元府",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [39, 51, 56],
    waterAdjacent: [],
    adjacentThroughMountainPass: [33,],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 12,
    cityID: 24,
    x: 133,
    y: 158
}, {
    id: 53,
    name: "邛崃山羁縻州地区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [57,],
    waterAdjacent: [54,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 12,
    cityID: 0,
    x: 78,
    y: 210
}, {
    id: 54,
    name: "成都府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [51, 55],
    waterAdjacent: [53, 57],
    adjacentThroughMountainPass: [51,],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 12,
    cityID: 25,
    x: 93,
    y: 193
}, {
    id: 55,
    name: "潼川府",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [54, 56,],
    waterAdjacent: [57,],
    adjacentThroughMountainPass: [51,],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 12,
    cityID: 26,
    x: 115,
    y: 198
}, {
    id: 56,
    name: "夔州都督府辖区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [52, 55],
    waterAdjacent: [57, 58, 62, 63, 59,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 12,
    cityID: 0,
    x: 150,
    y: 193
}, {
    id: 57,
    name: "乌蒙山羁縻州地区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [53, 58],
    waterAdjacent: [54, 55, 56],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 12,
    cityID: 0,
    x: 104,
    y: 232
}, {
    id: 58,
    name: "黔州地区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [57,],
    waterAdjacent: [56,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 12,
    cityID: 0,
    x: 152,
    y: 232
}, {
    id: 59,
    name: "三峡地区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [60, 63],
    waterAdjacent: [42, 56],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 13,
    cityID: 0,
    x: 181,
    y: 187
}, {
    id: 60,
    name: "江陵府",
    terrainType: "TerrainType.SWAMP",
    landAdjacent: [59, 63],
    waterAdjacent: [42, 61, 64, 65],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 13,
    cityID: 27,
    x: 204,
    y: 200
}, {
    id: 61,
    name: "德安府",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [41, 42, 49],
    waterAdjacent: [60, 65],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 13,
    cityID: 28,
    x: 216,
    y: 179
}, {
    id: 62,
    name: "武陵山区",
    terrainType: "TerrainType.MOUNTAINS",
    landAdjacent: [63, 64],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 13,
    cityID: 0,
    x: 171,
    y: 224
}, {
    id: 63,
    name: "鼎州地区",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [59, 60, 62],
    waterAdjacent: [56, 64],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 13,
    cityID: 0,
    x: 184,
    y: 206
}, {
    id: 64,
    name: "荆湖南路",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [62, 65, 71],
    waterAdjacent: [60, 63],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 13,
    cityID: 29,
    x: 200,
    y: 232
}, {
    id: 65,
    name: "鄂州地区",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [64, 68],
    waterAdjacent: [49, 60, 61],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 13,
    cityID: 0,
    x: 213,
    y: 205
}, {
    id: 66,
    name: "江宁府",
    terrainType: "TerrainType.SWAMP",
    landAdjacent: [72, 73, 74, 67],
    waterAdjacent: [46, 50],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 14,
    cityID: 30,
    x: 278,
    y: 185
}, {
    id: 67,
    name: "黄山地区",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [66, 70, 74, 76],
    waterAdjacent: [69,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 14,
    cityID: 0,
    x: 268,
    y: 200
}, {
    id: 68,
    name: "洪洲地区",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [65, 69],
    waterAdjacent: [49, 70, 71],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 14,
    cityID: 31,
    x: 229,
    y: 213
}, {
    id: 69,
    name: "彭蠡湖区",
    terrainType: "TerrainType.SWAMP",
    landAdjacent: [68,],
    waterAdjacent: [49, 50, 67, 70],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 14,
    cityID: 0,
    x: 244,
    y: 206
}, {
    id: 70,
    name: "鄱阳湖平原",
    terrainType: "TerrainType.FLATLAND",
    landAdjacent: [67, 71, 76, 77],
    waterAdjacent: [69,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 14,
    cityID: 0,
    x: 263,
    y: 220
}, {
    id: 71,
    name: "江南丘陵",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [64, 70, 77],
    waterAdjacent: [68,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 14,
    cityID: 0,
    x: 234,
    y: 239
}, {
    id: 72,
    name: "镇江府",
    terrainType: "TerrainType.SWAMP",
    landAdjacent: [66,],
    waterAdjacent: [73,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 15,
    cityID: 32,
    x: 293,
    y: 175
}, {
    id: 73,
    name: "平江府",
    terrainType: "TerrainType.SWAMP",
    landAdjacent: [66, 74],
    waterAdjacent: [72,],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 15,
    cityID: 33,
    x: 303,
    y: 184
}, {
    id: 74,
    name: "临安府",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [66, 67, 73, 75, 76],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 15,
    cityID: 34,
    x: 282,
    y: 203
}, {
    id: 75,
    name: "越州",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [74, 76],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 15,
    cityID: 0,
    x: 294,
    y: 208
}, {
    id: 76,
    name: "两浙路南部",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [67, 70, 74, 75, 76, 77],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !1,
    provinceID: 15,
    cityID: 0,
    x: 290,
    y: 224
}, {
    id: 77,
    name: "福建路",
    terrainType: "TerrainType.HILLS",
    landAdjacent: [70, 71, 76],
    waterAdjacent: [],
    adjacentThroughMountainPass: [],
    adjacentForeignCountries: [],
    hasCity: !0,
    provinceID: 16,
    cityID: 35,
    x: 277,
    y: 241
},];

const cities = [
    {
        id:1,
        name:"大同",
        province:1,
        colonizeLevel:0,
        region:2,
        capital:true,
    },
    {
        id:2,
        name:"大定",
        province:2,
        colonizeLevel:0,
        region:5,
        capital:true,
    },
    {
        id:3,
        name:"辽阳",
        province:3,
        colonizeLevel:0,
        region:6,
        capital:true,
    },
    {
        id:4,
        name:"析津",
        province:4,
        colonizeLevel:0,
        region:7,
        capital:false,
    },
    {
        id:5,
        name:"阳曲",
        province:5,
        colonizeLevel:1,
        region:10,
        capital:true,
    },
    {
        id:6,
        name:"临汾",
        province:5,
        colonizeLevel:1,
        region:11,
        capital:false,
    },
    {
        id:7,
        name:"上党",
        province:5,
        colonizeLevel:1,
        region:12,
        capital:false,
    },
    {
        id:8,
        name:"真定",
        province:6,
        colonizeLevel:1,
        region:13,
        capital:false,
    },
    {
        id:9,
        name:"安喜",
        province:6,
        colonizeLevel:0,
        region:14,
        capital:false,
    },
    {
        id:10,
        name:"河间",
        province:6,
        colonizeLevel:1,
        region:15,
        capital:false,
    },
    {
        id:11,
        name:"元城",
        province:6,
        colonizeLevel:1,
        region:18,
        capital:true,
    },
    {
        id:12,
        name:"历城",
        province:7,
        colonizeLevel:1,
        region:21,
        capital:false,
    },
    {
        id:13,
        name:"须城",
        province:7,
        colonizeLevel:2,
        region:25,
        capital:false,
    },
    {
        id:14,
        name:"宋城",
        province:7,
        colonizeLevel:1,
        region:28,
        capital:true,
    },
    {
        id:15,
        name:"肤施",
        province:8,
        colonizeLevel:1,
        region:32,
        capital:false,
    },
    {
        id:16,
        name:"天兴",
        province:8,
        colonizeLevel:2,
        region:33,
        capital:false,
    },
    {
        id:17,
        name:"长安",
        province:8,
        colonizeLevel:2,
        region:36,
        capital:true,
    },
    {
        id:18,
        name:"洛阳",
        province:9,
        colonizeLevel:2,
        region:37,
        capital:false,
    },
    {
        id:19,
        name:"宛丘",
        province:9,
        colonizeLevel:2,
        region:41,
        capital:false,
    },
    {
        id:20,
        name:"襄阳",
        province:9,
        colonizeLevel:3,
        region:42,
        capital:true,
    },
    {
        id:21,
        name:"开封",
        province:10,
        colonizeLevel:2,
        region:43,
        capital:true,
    },
    {
        id:22,
        name:"江都",
        province:11,
        colonizeLevel:3,
        region:46,
        capital:true,
    },
    {
        id:23,
        name:"下蔡",
        province:11,
        colonizeLevel:3,
        region:48,
        capital:false,
    },
    {
        id:24,
        name:"南郑",
        province:12,
        colonizeLevel:3,
        region:52,
        capital:false,
    },
    {
        id:25,
        name:"成都",
        province:12,
        colonizeLevel:4,
        region:54,
        capital:true,
    },
    {
        id:26,
        name:"郪县",
        province:12,
        colonizeLevel:4,
        region:55,
        capital:false,
    },
    {
        id:27,
        name:"江陵",
        province:13,
        colonizeLevel:4,
        region:60,
        capital:true,
    },
    {
        id:28,
        name:"安陆",
        province:13,
        colonizeLevel:3,
        region:61,
        capital:false,
    },
    {
        id:29,
        name:"长沙",
        province:13,
        colonizeLevel:4,
        region:64,
        capital:false,
    },
    {
        id:30,
        name:"江宁",
        province:14,
        colonizeLevel:4,
        region:66,
        capital:true,
    },
    {
        id:31,
        name:"南昌",
        province:14,
        colonizeLevel:4,
        region:68,
        capital:false,
    },
    {
        id:32,
        name:"丹徒",
        province:15,
        colonizeLevel:5,
        region:72,
        capital:true,
    },
    {
        id:33,
        name:"吴县",
        province:15,
        colonizeLevel:5,
        region:73,
        capital:false,
    },
    {
        id:34,
        name:"钱塘",
        province:15,
        colonizeLevel:5,
        region:74,
        capital:true,
    },
    {
        id:35,
        name:"闽县",
        province:16,
        colonizeLevel:5,
        region:77,
        capital:true,
    },
]

const provinces = [{
    id: 1,
    name: "西京路",
    adjacent: [2, 4, 5],
    capital: [1],
    otherCities: [],
    adjacentForeignCountries: [],
},
    {
        id: 2,
        name: "北京路",
        adjacent: [1, 3, 4],
        capital: [2],
        otherCities: [],
        adjacentForeignCountries: [],
    },
    {
        id: 3,
        name: "燕京路",
        adjacent: [2, 4],
        capital: [],
        otherCities: [4],
        adjacentForeignCountries: [],
    },
    {
        id: 4,
        name: "东京路",
        adjacent: [1, 2, 6],
        capital: [3],
        otherCities: [],
        adjacentForeignCountries: [],
    },
    {
        id: 5,
        name: "河东路",
        adjacent: [1, 6, 8, 9, 10],
        capital: [5],
        otherCities: [6, 7],
        adjacentForeignCountries: [],
    },
    {
        id: 6,
        name: "河北两路",
        adjacent: [1, 4, 5, 7, 9, 10],
        capital: [11],
        otherCities: [8, 9, 10],
        adjacentForeignCountries: [],
    },
    {
        id: 7,
        name: "京东两路",
        adjacent: [6, 10, 11],
        capital: [14],
        otherCities: [12, 13],
        adjacentForeignCountries: [],
    },
    {
        id: 8,
        name: "陕西六路",
        adjacent: [5, 9, 12],
        capital: [17],
        otherCities: [15, 16],
        adjacentForeignCountries: [],
    },
    {
        id: 9,
        name: "京西两路",
        adjacent: [5, 6, 8, 10, 11, 12, 13],
        capital: [20],
        otherCities: [18, 19],
        adjacentForeignCountries: [],
    },
    {
        id: 10,
        name: "京畿路",
        adjacent: [6, 7, 9, 11],
        capital: [21],
        otherCities: [],
        adjacentForeignCountries: [],
    },
    {
        id: 11,
        name: "淮南两路",
        adjacent: [7, 9, 10, 13, 14, 15],
        capital: [22],
        otherCities: [23],
        adjacentForeignCountries: [],
    },
    {
        id: 12,
        name: "川陕四路",
        adjacent: [8, 9, 13],
        capital: [25],
        otherCities: [24, 26],
        adjacentForeignCountries: [],
    },
    {
        id: 13,
        name: "荆湖两路",
        adjacent: [9, 11, 12, 14],
        capital: [27],
        otherCities: [28, 29],
        adjacentForeignCountries: [],
    },
    {
        id: 14,
        name: "江南两路",
        adjacent: [11, 13, 15, 16],
        capital: [30],
        otherCities: [31],
        adjacentForeignCountries: [],
    },
    {
        id: 15,
        name: "两浙路",
        adjacent: [11, 14, 16],
        capital: [32, 34],
        otherCities: [33],
        adjacentForeignCountries: [],
    },
    {
        id: 16,
        name: "福建路",
        adjacent: [14, 15],
        capital: [35],
        otherCities: [],
        adjacentForeignCountries: [],
    },]

const provinceIDsArray = [
    "",
    "ProvinceID.XIJINGLU",
    "ProvinceID.BEIJINGLU",
    "ProvinceID.YANJINGLU",
    "ProvinceID.DONGJINGLU",
    "ProvinceID.HEDONGLU",
    "ProvinceID.HEBEILIANGLU",
    "ProvinceID.JINGDONGLIANGLU",
    "ProvinceID.JINGXILIANGLU",
    "ProvinceID.JINGJILU",
    "ProvinceID.HUAINANLIANGLU",
    "ProvinceID.CHUANSHANSILU",
    "ProvinceID.JINHULIANGLU",
    "ProvinceID.JIANGNANLIANGLU",
    "ProvinceID.LIANGZHELU",
    "ProvinceID.FUJIANLU",
    "ProvinceID.SHANXILIULU",
];

function rid(id) {
    return `RegionID.R${id.toString().padStart(2, '0')}`;
}

const cityIDsArray = [
    "",
    "CityID.DaTong",
    "CityID.DaDing",
    "CityID.LiaoYang",
    "CityID.XiJin",
    "CityID.YangQu",
    "CityID.LinFen",
    "CityID.ShangDang",
    "CityID.ZhenDing",
    "CityID.AnXi",
    "CityID.HeJian",
    "CityID.YuanCheng",
    "CityID.LiCheng",
    "CityID.XuCheng",
    "CityID.SongCheng",
    "CityID.Fushi",
    "CityID.TianXing",
    "CityID.ChangAn",
    "CityID.LuoYang",
    "CityID.WanQiu",
    "CityID.XiangYang",
    "CityID.KaiFeng",
    "CityID.JiangDu",
    "CityID.XiaCai",
    "CityID.NanZhen",
    "CityID.ChengDu",
    "CityID.QiXian",
    "CityID.JiangLing",
    "CityID.AnLu",
    "CityID.ChangSha",
    "CityID.JiangNing",
    "CityID.NanChang",
    "CityID.DanTu",
    "CityID.WuXian",
    "CityID.QianTang",
    "CityID.MinXian",
];

cities.forEach((e)=>{
    let strid = cityIDsArray[e.id];
    let t= `[${strid}]:{id:${strid},`;
    t += `name:"${e.name}",`;
    t += `capital:${e.capital},`;
    t += `province:${provinceIDsArray[e.province]},`;
    t += `colonizeLevel:${e.colonizeLevel},`
    t += `region:${rid(e.region)}},`
    console.log(t);
})
console.log("\n\n\n");
provinces.forEach((e)=>{
    let t = `[${provinceIDsArray[e.id]}]:{id:${provinceIDsArray[e.id]},`
    t += `name:"${e.name}",`;
    t += `capital:${cityIDsArray[e.capital]},`
    t += `adjacent:[${e.adjacent.map((r)=>rid(r)).join(',')}],`;
    t += `other:[${e.otherCities.map((r)=>cityIDsArray[r]).join(',')}]},`;
    console.log(t);
})
console.log("\n\n\n");

regions.forEach((e) => {
    let t = `[${rid(e.id)}]:{id:${rid(e.id)},name:"${e.name}",terrain:${e.terrainType},`;
    t+= `province:${provinceIDsArray[e.provinceID]},`;
    t += `land:[${e.landAdjacent.map((r)=>rid(r)).join(',')}],`;
    t += `water:[${e.waterAdjacent.map((r)=>rid(r)).join(',')}],`;
    t += `water:[${e.adjacentThroughMountainPass.map((r)=>rid(r)).join(',')}],`;
    if (e.cityID === 0) {
        t += 'city:null},';
    } else {
        t += `city:${cityIDsArray[e.cityID]}},`
    }
    console.log(t);
})

