FROM larry801/filmcentenary-builder AS builder
COPY . .
RUN yarn build --profile
RUN tsc-bundle tsconfig.server.json

FROM larry801/filmcentenary-base
COPY --from=builder /app/build  /app/build
CMD node build/bundle.js
