FROM larry801/film-centenary-builder AS builder
COPY . .
RUN yarn build
RUN tsc-bundle tsconfig.server.json

FROM larry801/film-centenary-base
COPY --from=builder /app/build  /app/build
CMD node build/bundle.js
