import {
    BasicCardID,
    CardCategory,
    CardType,
    cost, EventCardID,
    ICost,
    IEffect,
    IEra,
    IEventCard,
    IFilmCard,
    INormalOrLegendCard,
    IPersonCard,
    ISchoolCard,
    Region
} from "./core";
import {getBasicCard} from "../constant/cards/basic";
import {eventCardById} from "../constant/cards/event";


interface IArgFilmCard {
    era: IEra,
    region: Region,
    name: string,
    cardId: string,
    cost: ICost,
    vp: number,
    category: CardCategory,
    industry: number,
    aesthetics: number,
}

interface IArgEvent {
    name: string,
    id: string,
    effect: IEffect,
    era: IEra,
}

export function filmCard(arg: IArgFilmCard
): IFilmCard {
    return {
        cost: arg.cost,
        aesthetics: arg.aesthetics,
        cardId: arg.cardId,
        category: arg.category,
        industry: arg.industry,
        name: arg.name,
        type: CardType.F, era: arg.era, region: arg.region,
        vp: arg.vp
    }
}

export function personCard(arg: IArgFilmCard): IPersonCard {
    return {
        type: CardType.P, era: arg.era, region: arg.region,
        industry: arg.industry,
        vp: arg.vp,
        cost: arg.cost,
        name: arg.name,
        cardId: arg.cardId,
        category: arg.category,
        aesthetics: arg.aesthetics
    }
}

export function schoolCard(arg: IArgFilmCard): ISchoolCard {
    return {
        era: arg.era, region: arg.region,
        type: CardType.S,
        industry: arg.industry,
        vp: arg.vp,
        cost: arg.cost,
        name: arg.name,
        cardId: arg.cardId,
        category: arg.category,
        aesthetics: arg.aesthetics
    }
}

export function eventCard(arg: IArgEvent): IEventCard {
    return {
        region: Region.NONE,
        cost: cost(0, 0, 0),
        category: CardCategory.BASIC,
        type: CardType.E,
        era: arg.era,
        name: arg.name,
        effect: arg.effect,
        cardId: arg.id
    }
}

// eslint-disable-next-line
const NoneBasicCards = {
    "P1101": personCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "大卫·格里菲斯",
        cardId: "P1101",
        cost: cost(5, 0, 2),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P1102": personCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "托马斯·爱迪生",
        cardId: "P1102",
        cost: cost(5, 2, 0),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F1103": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "党同伐异",
        cardId: "F1103",
        cost: cost(4, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1104": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "火车大劫案",
        cardId: "F1104",
        cost: cost(5, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1105": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "爵士歌王",
        cardId: "F1105",
        cost: cost(3, 2, 0),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1106": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "将军号",
        cardId: "F1106",
        cost: cost(3, 1, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F1107": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "淘金记",
        cardId: "F1107",
        cost: cost(2, 0, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F1108": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "北方的纳努克",
        cardId: "F1108",
        cost: cost(3, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F1109": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "金刚",
        cardId: "F1109",
        cost: cost(3, 3, 0),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1110": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "贪婪",
        cardId: "F1110",
        cost: cost(0, 0, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "P1201": personCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "乔治·梅里爱",
        cardId: "P1201",
        cost: cost(5, 2, 0),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P1202": personCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "卢米埃尔兄弟",
        cardId: "P1202",
        cost: cost(5, 2, 0),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "S1203": schoolCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "表现主义",
        cardId: "S1203",
        cost: cost(4, 0, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "S1204": schoolCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "瑞典学派",
        cardId: "S1204",
        cost: cost(4, 2, 2),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1205": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "诺斯费拉杜",
        cardId: "F1205",
        cost: cost(2, 1, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F1206": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "圣女贞德蒙难记",
        cardId: "F1206",
        cost: cost(2, 0, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F1207": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "月球旅行记",
        cardId: "F1207",
        cost: cost(4, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1208": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "大都会",
        cardId: "F1208",
        cost: cost(3, 2, 2),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F1209": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "幽灵马车",
        cardId: "F1209",
        cost: cost(2, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1210": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "工厂大门",
        cardId: "F1210",
        cost: cost(3, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F1211": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "吉斯公爵遇剌记",
        cardId: "F1211",
        cost: cost(3, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "S1301": schoolCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "蒙太奇学派",
        cardId: "S1301",
        cost: cost(4, 1, 3),
        vp: 4,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 1,
    }),
    "P1302": personCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "谢尔盖·爱森斯坦",
        cardId: "P1302",
        cost: cost(5, 0, 2),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "S1303": schoolCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "电影眼睛派",
        cardId: "S1303",
        cost: cost(1, 3, 1),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F1304": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "母亲",
        cardId: "F1304",
        cost: cost(3, 0, 2),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F1305": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "战舰波将金号",
        cardId: "F1305",
        cost: cost(3, 1, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F1306": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "持摄影机的人",
        cardId: "F1306",
        cost: cost(3, 1, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1307": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "谢尔盖神父",
        cardId: "F1307",
        cost: cost(3, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "S2101": schoolCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "古典好莱坞",
        cardId: "S2101",
        cost: cost(7, 6, 2),
        vp: 8,
        category: CardCategory.LEGEND,
        industry: 2,
        aesthetics: 0,
    }),
    "P2102": personCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "约翰·福特",
        cardId: "P2102",
        cost: cost(8, 5, 1),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P2103": personCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "阿尔弗雷德·希区柯克",
        cardId: "P2103",
        cost: cost(8, 4, 2),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F2104": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "黑色电影",
        cardId: "F2104",
        cost: cost(6, 4, 2),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "P2105": personCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "奥尔逊威尔斯",
        cardId: "P2105",
        cost: cost(6, 0, 4),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F2106": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "乱世佳人",
        cardId: "F2106",
        cost: cost(7, 6, 0),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F2107": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "关山飞度",
        cardId: "F2107",
        cost: cost(5, 5, 1),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2108": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "雨中曲",
        cardId: "F2108",
        cost: cost(5, 3, 3),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2109": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "公民凯恩",
        cardId: "F2109",
        cost: cost(7, 0, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F2110": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "白热",
        cardId: "F2110",
        cost: cost(5, 4, 0),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2111": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "日落大道",
        cardId: "F2111",
        cost: cost(4, 4, 2),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2112": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "宾虚",
        cardId: "F2112",
        cost: cost(6, 6, 0),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F2113": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "马耳他之鹰",
        cardId: "F2113",
        cost: cost(5, 3, 3),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2114": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "迷魂记",
        cardId: "F2114",
        cost: cost(4, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "S2201": schoolCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "新现实主义",
        cardId: "S2201",
        cost: cost(8, 0, 6),
        vp: 8,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 1,
    }),
    "P2202": personCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "费德里科·费里尼",
        cardId: "P2202",
        cost: cost(8, 1, 5),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P2203": personCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "大卫·里恩",
        cardId: "P2203",
        cost: cost(7, 5, 3),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "S2204": schoolCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "诗意现实主义",
        cardId: "S2204",
        cost: cost(7, 2, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "P2205": personCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "让·雷诺阿",
        cardId: "P2205",
        cost: cost(7, 0, 4),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F2206": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "游戏规则",
        cardId: "F2206",
        cost: cost(6, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2207": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "偷自行车的人",
        cardId: "F2207",
        cost: cost(8, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2208": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "M就是凶手",
        cardId: "F2208",
        cost: cost(6, 4, 0),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2209": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "大路",
        cardId: "F2209",
        cost: cost(5, 1, 5),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2210": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "乡村牧师日记",
        cardId: "F2210",
        cost: cost(4, 0, 6),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2211": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "拿破仑",
        cardId: "F2211",
        cost: cost(4, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2212": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "天色破晓",
        cardId: "F2212",
        cost: cost(4, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2213": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "恐惧的代价",
        cardId: "F2213",
        cost: cost(5, 3, 3),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2214": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "阿拉伯的劳伦斯",
        cardId: "F2214",
        cost: cost(5, 5, 3),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "S2301": schoolCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "社会主义现实主义",
        cardId: "S2301",
        cost: cost(8, 4, 4),
        vp: 6,
        category: CardCategory.LEGEND,
        industry: 1,
        aesthetics: 1,
    }),
    "P2302": personCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "米哈伊尔·卡拉托佐夫",
        cardId: "P2302",
        cost: cost(8, 3, 3),
        vp: 5,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F2303": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "夏伯阳",
        cardId: "F2303",
        cost: cost(7, 1, 1),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2304": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "士兵之歌",
        cardId: "F2304",
        cost: cost(6, 2, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F2305": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "雁南飞",
        cardId: "F2305",
        cost: cost(6, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2306": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "下水道",
        cardId: "F2306",
        cost: cost(7, 3, 2),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2307": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "被遗忘的祖先的阴影",
        cardId: "F2307",
        cost: cost(4, 0, 6),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F2308": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "静静的顿河",
        cardId: "F2308",
        cost: cost(6, 4, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2309": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "大地",
        cardId: "F2309",
        cost: cost(6, 0, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "P2401": personCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "黑泽明",
        cardId: "P2401",
        cost: cost(8, 3, 3),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P2402": personCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "蔡楚生",
        cardId: "P2402",
        cost: cost(6, 4, 4),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F2403": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "小城之春",
        cardId: "F2403",
        cost: cost(6, 0, 5),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2404": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "—江春水向东流",
        cardId: "F2404",
        cost: cost(7, 2, 0),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2405": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "东京物语",
        cardId: "F2405",
        cost: cost(6, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2406": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "七武士",
        cardId: "F2406",
        cost: cost(6, 4, 0),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2407": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "大地之歌",
        cardId: "F2407",
        cost: cost(6, 1, 1),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F2408": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "神女",
        cardId: "F2408",
        cost: cost(5, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2409": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "浮云",
        cardId: "F2409",
        cost: cost(4, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2410": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "我这一辈子",
        cardId: "F2410",
        cost: cost(5, 2, 0),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "S3101": schoolCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "新好莱坞电影",
        cardId: "S3101",
        cost: cost(10, 10, 2),
        vp: 13,
        category: CardCategory.LEGEND,
        industry: 2,
        aesthetics: 2,
    }),
    "P3102": personCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "史蒂文·斯皮尔伯格",
        cardId: "P3102",
        cost: cost(9, 9, 5),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F3103": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "教父",
        cardId: "F3103",
        cost: cost(10, 8, 8),
        vp: 11,
        category: CardCategory.LEGEND,
        industry: 1,
        aesthetics: 2,
    }),
    "F3104": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "星球大战",
        cardId: "F3104",
        cost: cost(9, 10, 0),
        vp: 13,
        category: CardCategory.LEGEND,
        industry: 3,
        aesthetics: 0,
    }),
    "S3105": schoolCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "纽约派",
        cardId: "S3105",
        cost: cost(9, 4, 4),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 4,
    }),
    "F3106": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "马丁·斯科塞斯",
        cardId: "F3106",
        cost: cost(10, 5, 5),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F3107": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "罗杰·科曼",
        cardId: "F3107",
        cost: cost(10, 6, 0),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F3108": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "泰坦尼克号",
        cardId: "F3108",
        cost: cost(9, 12, 0),
        vp: 15,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F3109": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "2001太空漫游",
        cardId: "F3109",
        cost: cost(8, 7, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 2,
    }),
    "F3110": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "驱魔人",
        cardId: "F3110",
        cost: cost(8, 8, 2),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3111": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "邦尼和克莱德",
        cardId: "F3111",
        cost: cost(10, 5, 4),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3112": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "出租车司机",
        cardId: "F3112",
        cost: cost(8, 5, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F3113": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "夺宝奇兵",
        cardId: "F3113",
        cost: cost(9, 10, 0),
        vp: 13,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F3114": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "最长的一码",
        cardId: "F3114",
        cost: cost(9, 10, 0),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3115": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "虎豹小霸王",
        cardId: "F3115",
        cost: cost(8, 6, 2),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3116": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "闪灵",
        cardId: "F3116",
        cost: cost(8, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "S3201": schoolCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "新浪潮",
        cardId: "S3201",
        cost: cost(9, 4, 10),
        vp: 3,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 3,
    }),
    "P3202": personCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "弗朗索瓦·特吕弗",
        cardId: "P3202",
        cost: cost(10, 5, 7),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P3203": personCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "英格玛·伯格曼",
        cardId: "P3203",
        cost: cost(10, 0, 10),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "S3204": schoolCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "左岸派",
        cardId: "S3204",
        cost: cost(7, 8, 0),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 3,
    }),
    "F3205": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "独行杀手",
        cardId: "F3205",
        cost: cost(8, 6, 8),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3206": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "陆上行舟",
        cardId: "F3206",
        cost: cost(8, 8, 2),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3207": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "去年在马里昂巴德",
        cardId: "F3207",
        cost: cost(9, 0, 10),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 3,
    }),
    "F3208": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "八部半",
        cardId: "F3208",
        cost: cost(8, 0, 12),
        vp: 13,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 3,
    }),
    "F3209": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "朱尔与吉姆",
        cardId: "F3209",
        cost: cost(7, 4, 9),
        vp: 15,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3210": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "007：黄金眼",
        cardId: "F3210",
        cost: cost(9, 9, 0),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F3211": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "流浪艺人",
        cardId: "F3211",
        cost: cost(8, 0, 9),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3212": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "假面",
        cardId: "F3212",
        cost: cost(6, 3, 9),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F3213": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "小孩与鹰",
        cardId: "F3213",
        cost: cost(7, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "P3301": personCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "安德烈·塔尔科夫斯基",
        cardId: "P3301",
        cost: cost(9, 4, 10),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P3302": personCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "尼基塔·米哈尔科夫",
        cardId: "P3302",
        cost: cost(9, 8, 6),
        vp: 8,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F3303": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "战争与和平",
        cardId: "F3303",
        cost: cost(8, 10, 4),
        vp: 13,
        category: CardCategory.LEGEND,
        industry: 2,
        aesthetics: 0,
    }),
    "F3304": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "地下",
        cardId: "F3304",
        cost: cost(9, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3305": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "西伯利亚理发师",
        cardId: "F3305",
        cost: cost(8, 8, 4),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3306": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "办公室的故事",
        cardId: "F3306",
        cost: cost(9, 3, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F3307": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "蓝",
        cardId: "F3307",
        cost: cost(9, 0, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 2,
    }),
    "F3308": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "红军与白军",
        cardId: "F3308",
        cost: cost(8, 3, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3309": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "索拉里斯",
        cardId: "F3309",
        cost: cost(6, 4, 8),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3310": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "普通法西斯",
        cardId: "F3310",
        cost: cost(8, 3, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3311": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "钻石胳膊",
        cardId: "F3311",
        cost: cost(7, 4, 4),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F3312": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "乱世英豪",
        cardId: "F3312",
        cost: cost(9, 7, 4),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "P3401": personCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "张艺谋",
        cardId: "P3401",
        cost: cost(10, 5, 5),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P3402": personCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "王家卫",
        cardId: "P3402",
        cost: cost(9, 4, 7),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P3403": personCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "阿巴斯·基亚罗斯塔米",
        cardId: "P3403",
        cost: cost(10, 0, 9),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F3404": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "悲情城市",
        cardId: "F3404",
        cost: cost(8, 4, 9),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F3405": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "重庆森林",
        cardId: "F3405",
        cost: cost(8, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3406": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "英雄本色",
        cardId: "F3406",
        cost: cost(8, 8, 3),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3407": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "寅次郎的故事",
        cardId: "F3407",
        cost: cost(8, 6, 2),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3408": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "红高粱",
        cardId: "F3408",
        cost: cost(7, 4, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3409": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "芙蓉镇",
        cardId: "F3409",
        cost: cost(8, 2, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3410": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "空山灵雨",
        cardId: "F3410",
        cost: cost(6, 4, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 8,
    }),
    "F3411": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "太白山脉",
        cardId: "F3411",
        cost: cost(5, 6, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3412": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "青春残酷物语",
        cardId: "F3412",
        cost: cost(7, 0, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F3413": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "小鞋子",
        cardId: "F3413",
        cost: cost(8, 2, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F3414": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "樱桃的滋味",
        cardId: "F3414",
        cost: cost(7, 0, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
}

const CARDS = {
    "1101": personCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "大卫·格里菲斯",
        cardId: "1101",
        cost: cost(5, 0, 2),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "1102": personCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "托马斯·爱迪生",
        cardId: "1102",
        cost: cost(5, 2, 0),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "1103": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "党同伐异",
        cardId: "1103",
        cost: cost(4, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "1104": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "火车大劫案",
        cardId: "1104",
        cost: cost(5, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "1105": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "爵士歌王",
        cardId: "1105",
        cost: cost(3, 2, 0),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "1106": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "将军号",
        cardId: "1106",
        cost: cost(3, 1, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "1107": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "淘金记",
        cardId: "1107",
        cost: cost(2, 0, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "1108": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "北方的纳努克",
        cardId: "1108",
        cost: cost(3, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "1109": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "金刚",
        cardId: "1109",
        cost: cost(3, 3, 0),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "1110": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "贪婪",
        cardId: "1110",
        cost: cost(0, 0, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "1201": personCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "乔治·梅里爱",
        cardId: "1201",
        cost: cost(5, 2, 0),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "1202": personCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "卢米埃尔兄弟",
        cardId: "1202",
        cost: cost(5, 2, 0),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "1203": schoolCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "表现主义",
        cardId: "1203",
        cost: cost(4, 0, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "1204": schoolCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "瑞典学派",
        cardId: "1204",
        cost: cost(4, 2, 2),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "1205": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "诺斯费拉杜",
        cardId: "1205",
        cost: cost(2, 1, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "1206": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "圣女贞德蒙难记",
        cardId: "1206",
        cost: cost(2, 0, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "1207": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "月球旅行记",
        cardId: "1207",
        cost: cost(4, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "1208": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "大都会",
        cardId: "1208",
        cost: cost(3, 2, 2),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "1209": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "幽灵马车",
        cardId: "1209",
        cost: cost(2, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "1210": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "工厂大门",
        cardId: "1210",
        cost: cost(3, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "1211": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "吉斯公爵遇剌记",
        cardId: "1211",
        cost: cost(3, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "1301": schoolCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "蒙太奇学派",
        cardId: "1301",
        cost: cost(4, 1, 3),
        vp: 4,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 1,
    }),
    "1302": personCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "谢尔盖·爱森斯坦",
        cardId: "1302",
        cost: cost(5, 0, 2),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "1303": schoolCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "电影眼睛派",
        cardId: "1303",
        cost: cost(1, 3, 1),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "1304": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "母亲",
        cardId: "1304",
        cost: cost(3, 0, 2),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "1305": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "战舰波将金号",
        cardId: "1305",
        cost: cost(3, 1, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "1306": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "持摄影机的人",
        cardId: "1306",
        cost: cost(3, 1, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "1307": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "谢尔盖神父",
        cardId: "1307",
        cost: cost(3, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "2101": schoolCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "古典好莱坞",
        cardId: "2101",
        cost: cost(7, 6, 2),
        vp: 8,
        category: CardCategory.LEGEND,
        industry: 2,
        aesthetics: 0,
    }),
    "2102": personCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "约翰·福特",
        cardId: "2102",
        cost: cost(8, 5, 1),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "2103": personCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "阿尔弗雷德·希区柯克",
        cardId: "2103",
        cost: cost(8, 4, 2),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "2104": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "黑色电影",
        cardId: "2104",
        cost: cost(6, 4, 2),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "2105": personCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "奥尔逊威尔斯",
        cardId: "2105",
        cost: cost(6, 0, 4),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "2106": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "乱世佳人",
        cardId: "2106",
        cost: cost(7, 6, 0),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "2107": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "关山飞度",
        cardId: "2107",
        cost: cost(5, 5, 1),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "2108": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "雨中曲",
        cardId: "2108",
        cost: cost(5, 3, 3),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2109": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "公民凯恩",
        cardId: "2109",
        cost: cost(7, 0, 3),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "2110": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "白热",
        cardId: "2110",
        cost: cost(5, 4, 0),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "2111": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "日落大道",
        cardId: "2111",
        cost: cost(4, 4, 2),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "2112": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "宾虚",
        cardId: "2112",
        cost: cost(6, 6, 0),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "2113": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "马耳他之鹰",
        cardId: "2113",
        cost: cost(5, 3, 3),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "2114": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "迷魂记",
        cardId: "2114",
        cost: cost(4, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2201": schoolCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "新现实主义",
        cardId: "2201",
        cost: cost(8, 0, 6),
        vp: 8,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 1,
    }),
    "2202": personCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "费德里科·费里尼",
        cardId: "2202",
        cost: cost(8, 1, 5),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "2203": personCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "大卫·里恩",
        cardId: "2203",
        cost: cost(7, 5, 3),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "2204": schoolCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "诗意现实主义",
        cardId: "2204",
        cost: cost(7, 2, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "2205": personCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "让·雷诺阿",
        cardId: "2205",
        cost: cost(7, 0, 4),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "2206": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "游戏规则",
        cardId: "2206",
        cost: cost(6, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2207": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "偷自行车的人",
        cardId: "2207",
        cost: cost(8, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "2208": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "M就是凶手",
        cardId: "2208",
        cost: cost(6, 4, 0),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "2209": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "大路",
        cardId: "2209",
        cost: cost(5, 1, 5),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2210": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "乡村牧师日记",
        cardId: "2210",
        cost: cost(4, 0, 6),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2211": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "拿破仑",
        cardId: "2211",
        cost: cost(4, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "2212": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "天色破晓",
        cardId: "2212",
        cost: cost(4, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2213": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "恐惧的代价",
        cardId: "2213",
        cost: cost(5, 3, 3),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "2214": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "阿拉伯的劳伦斯",
        cardId: "2214",
        cost: cost(5, 5, 3),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "2301": schoolCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "社会主义现实主义",
        cardId: "2301",
        cost: cost(8, 4, 4),
        vp: 6,
        category: CardCategory.LEGEND,
        industry: 1,
        aesthetics: 1,
    }),
    "2302": personCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "米哈伊尔·卡拉托佐夫",
        cardId: "2302",
        cost: cost(8, 3, 3),
        vp: 5,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "2303": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "夏伯阳",
        cardId: "2303",
        cost: cost(7, 1, 1),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "2304": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "士兵之歌",
        cardId: "2304",
        cost: cost(6, 2, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "2305": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "雁南飞",
        cardId: "2305",
        cost: cost(6, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2306": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "下水道",
        cardId: "2306",
        cost: cost(7, 3, 2),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "2307": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "被遗忘的祖先的阴影",
        cardId: "2307",
        cost: cost(4, 0, 6),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "2308": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "静静的顿河",
        cardId: "2308",
        cost: cost(6, 4, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "2309": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "大地",
        cardId: "2309",
        cost: cost(6, 0, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "2401": personCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "黑泽明",
        cardId: "2401",
        cost: cost(8, 3, 3),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "2402": personCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "蔡楚生",
        cardId: "2402",
        cost: cost(6, 4, 4),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "2403": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "小城之春",
        cardId: "2403",
        cost: cost(6, 0, 5),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2404": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "—江春水向东流",
        cardId: "2404",
        cost: cost(7, 2, 0),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "2405": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "东京物语",
        cardId: "2405",
        cost: cost(6, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2406": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "七武士",
        cardId: "2406",
        cost: cost(6, 4, 0),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "2407": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "大地之歌",
        cardId: "2407",
        cost: cost(6, 1, 1),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "2408": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "神女",
        cardId: "2408",
        cost: cost(5, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "2409": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "人间的条件",
        cardId: "2409",
        cost: cost(4, 3, 3),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "2410": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "我这一辈子",
        cardId: "2410",
        cost: cost(5, 2, 0),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "3101": schoolCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "新好莱坞电影",
        cardId: "3101",
        cost: cost(10, 10, 2),
        vp: 13,
        category: CardCategory.LEGEND,
        industry: 2,
        aesthetics: 2,
    }),
    "3102": personCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "史蒂文·斯皮尔伯格",
        cardId: "3102",
        cost: cost(9, 9, 5),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "3103": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "教父",
        cardId: "3103",
        cost: cost(10, 8, 8),
        vp: 11,
        category: CardCategory.LEGEND,
        industry: 1,
        aesthetics: 2,
    }),
    "3104": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "星球大战",
        cardId: "3104",
        cost: cost(9, 10, 0),
        vp: 13,
        category: CardCategory.LEGEND,
        industry: 3,
        aesthetics: 0,
    }),
    "3105": schoolCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "纽约派",
        cardId: "3105",
        cost: cost(9, 4, 4),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 4,
    }),
    "3106": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "马丁·斯科塞斯",
        cardId: "3106",
        cost: cost(10, 5, 5),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "3107": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "罗杰·科曼",
        cardId: "3107",
        cost: cost(10, 6, 0),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "3108": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "泰坦尼克号",
        cardId: "3108",
        cost: cost(9, 12, 0),
        vp: 15,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "3109": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "2001太空漫游",
        cardId: "3109",
        cost: cost(8, 7, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 2,
    }),
    "3110": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "驱魔人",
        cardId: "3110",
        cost: cost(8, 8, 2),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3111": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "邦尼和克莱德",
        cardId: "3111",
        cost: cost(10, 5, 4),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3112": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "出租车司机",
        cardId: "3112",
        cost: cost(8, 5, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "3113": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "夺宝奇兵",
        cardId: "3113",
        cost: cost(9, 10, 0),
        vp: 13,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "3114": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "最长的一码",
        cardId: "3114",
        cost: cost(9, 10, 0),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "3115": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "虎豹小霸王",
        cardId: "3115",
        cost: cost(8, 6, 2),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3116": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "闪灵",
        cardId: "3116",
        cost: cost(8, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "3201": schoolCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "新浪潮",
        cardId: "3201",
        cost: cost(9, 4, 10),
        vp: 3,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 3,
    }),
    "3202": personCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "弗朗索瓦·特吕弗",
        cardId: "3202",
        cost: cost(10, 5, 7),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "3203": personCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "英格玛·伯格曼",
        cardId: "3203",
        cost: cost(10, 0, 10),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "3204": schoolCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "左岸派",
        cardId: "3204",
        cost: cost(7, 8, 0),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 3,
    }),
    "3205": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "独行杀手",
        cardId: "3205",
        cost: cost(8, 6, 8),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "3206": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "陆上行舟",
        cardId: "3206",
        cost: cost(8, 8, 2),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "3207": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "去年在马里昂巴德",
        cardId: "3207",
        cost: cost(9, 0, 10),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 3,
    }),
    "3208": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "八部半",
        cardId: "3208",
        cost: cost(8, 0, 12),
        vp: 13,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 3,
    }),
    "3209": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "朱尔与吉姆",
        cardId: "3209",
        cost: cost(7, 4, 9),
        vp: 15,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3210": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "007：黄金眼",
        cardId: "3210",
        cost: cost(9, 9, 0),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "3211": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "奇遇",
        cardId: "3211",
        cost: cost(8, 0, 9),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "3212": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "假面",
        cardId: "3212",
        cost: cost(6, 3, 9),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "3213": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "小孩与鹰",
        cardId: "3213",
        cost: cost(7, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3301": personCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "安德烈·塔尔科夫斯基",
        cardId: "3301",
        cost: cost(9, 4, 10),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "3302": personCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "谢尔盖·邦达尔丘克",
        cardId: "3302",
        cost: cost(9, 10, 4),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "3303": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "蓝",
        cardId: "3303",
        cost: cost(9, 0, 11),
        vp: 14,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "3304": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "战争与和平",
        cardId: "3304",
        cost: cost(8, 10, 4),
        vp: 13,
        category: CardCategory.LEGEND,
        industry: 2,
        aesthetics: 0,
    }),
    "3305": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "地下",
        cardId: "3305",
        cost: cost(9, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3306": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "桥",
        cardId: "3306",
        cost: cost(8, 9, 3),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "3307": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "办公室的故事",
        cardId: "3307",
        cost: cost(9, 3, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "3308": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "红军与白军",
        cardId: "3308",
        cost: cost(8, 3, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3309": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "索拉里斯",
        cardId: "3309",
        cost: cost(6, 4, 8),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3310": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "普通法西斯",
        cardId: "3310",
        cost: cost(8, 3, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3311": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "钻石胳膊",
        cardId: "3311",
        cost: cost(7, 4, 4),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "3312": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "乱世英豪",
        cardId: "3312",
        cost: cost(9, 7, 4),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3401": personCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "张艺谋",
        cardId: "3401",
        cost: cost(10, 5, 5),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "3402": personCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "王家卫",
        cardId: "3402",
        cost: cost(9, 4, 7),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "3403": personCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "阿巴斯·基亚罗斯塔米",
        cardId: "3403",
        cost: cost(10, 0, 9),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "3404": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "霸王别姬",
        cardId: "3404",
        cost: cost(8, 4, 9),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "3405": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "重庆森林",
        cardId: "3405",
        cost: cost(8, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "3406": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "英雄本色",
        cardId: "3406",
        cost: cost(8, 8, 3),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "3407": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "寅次郎的故事",
        cardId: "3407",
        cost: cost(8, 6, 2),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "3408": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "红高粱",
        cardId: "3408",
        cost: cost(7, 4, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "3409": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "芙蓉镇",
        cardId: "3409",
        cost: cost(8, 2, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "3410": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "侠女",
        cardId: "3410",
        cost: cost(6, 4, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 8,
    }),
    "3411": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "西便制",
        cardId: "3411",
        cost: cost(7, 3, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "3412": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "青春残酷物语",
        cardId: "3412",
        cost: cost(7, 0, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "3413": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "风柜来的人",
        cardId: "3413",
        cost: cost(8, 0, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "3414": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "樱桃的滋味",
        cardId: "3414",
        cost: cost(7, 0, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
}

export function getCardById(id: string): INormalOrLegendCard {
    if (id in CARDS) {
        // @ts-ignore
        return CARDS[id];
    } else {
        if (id in BasicCardID) {
            // @ts-ignore
            return getBasicCard(id as BasicCardID);
        } else {
            if (id in EventCardID) {
                return eventCardById(id as EventCardID);
            } else {
                throw new Error("No such id" + id)
            }
        }
    }
}

export function schoolCardsByEra(e: IEra) {
    let cards = Object.entries(CARDS);
    let res = cards.filter(c => c[1].era === e).filter(c => c[1].type === CardType.S)
    return res.map(c => c[1]);
}

export function filmCardsByEra(e: IEra) {
    let cards = Object.entries(CARDS);
    let res = cards.filter(c => c[1].era === e).filter(c => c[1].type === CardType.F)
    return res.map(c => c[1]);
}

export function cardsByCond(r: Region, e: IEra, isLegend: boolean = false): INormalOrLegendCard[] {
    let cards = Object.entries(CARDS);
    let res = cards.filter(c => c[1].era === e).filter(c => c[1].region === r)

    if (isLegend) {
        res = res.filter(c => c[1].category === CardCategory.LEGEND)
    } else {
        res = res.filter(c => c[1].category === CardCategory.NORMAL)
    }
    return res.map(c => c[1]);
}
