import {PlayerID} from "boardgame.io";

export enum Region {
    NA,
    WE,
    EE,
    ASIA,
    NONE,
}

export enum GameTurnOrder {
    FIXED = "FIXED",
    FIRST_RANDOM = "FIRST_RANDOM",
    ALL_RANDOM = "ALL_RANDOM",
}

export enum ClassicFilmAutoMoveMode {
    NO_AUTO = "NO_AUTO",
    DRAW_CARD = "DRAW_CARD",
    AESTHETICS_AWARD = "AESTHETICS_AWARD",
}
export enum GameMode {
    NORMAL = "NORMAL",
    NEWBIE = "NEWBIE",
    TEAM2V2 = "TEAM2V2",
}

export enum CardType {
    E,//event
    F,//film
    S,//school
    P,//people
    V,//scoring
}

export type CardID = BasicCardID | ClassicCardID | ScoreCardID | EventCardID;

export interface ICardSlot {
    region: Region,
    isLegend: boolean,
    card: ClassicCardID | null,
    comment: BasicCardID | null,
}

export enum IEra {
    ONE,
    TWO,
    THREE,
}

export interface IEffect {
    e: EffectNames,
    a: number | CardID | IEffect[]
}

export interface IBuyInfo {
    buyer: PlayerID,
    target: CardID,
    resource: number,
    deposit: number,
    helper: CardID[],
}

export enum CardCategory {
    SCORE,
    BASIC,
    NORMAL,
    LEGEND,
}

export interface ICard {
    cost: ICost,
    cardId: CardID,
    name: string,
    region: Region,
    type: CardType,
    category: CardCategory,
}

export function cost(r: number, i: number, a: number): ICost {
    return {
        res: r,
        industry: i,
        aesthetics: a,
    }
}

export interface INormalOrLegendCard extends ICard {
    category: CardCategory,
    type: CardType,
    cost: ICost,
    vp: number,
    industry: number,
    aesthetics: number,
    region: Region,
    era: IEra,
}

export interface IBasicCard extends ICard {
    category: CardCategory.BASIC,
    cost: ICost,
    vp: number,
    industry: number,
    aesthetics: number,
}

export interface ISchoolCard extends INormalOrLegendCard {
    type: CardType.S,
}

export interface IFilmCard extends INormalOrLegendCard {
    type: CardType.F,
}

export type EffectNames = SimpleEffectNames | ScoringEffectNames | NoExecutorEffectNames | ItrEffects;

export enum ItrEffects {
    aestheticsLevelUpCost = "aestheticsLevelUpCost",
    industryLevelUpCost = "industryLevelUpCost",
    payAdditionalCost = "payAdditionalCost",
    buildingNA = "buildingNA",
    era = "era",
    breakthroughResDeduct = "breakthroughResDeduct",
    alternative = "alternative",
    competition = "competition",
    loseAnyRegionShare = "loseAnyRegionShare",
    anyRegionShare = "anyRegionShare",
    anyRegionShareCompetition = "anyRegionShareCompetition",
    newHollyWoodEff = "newHollyWoodEff",
    anyRegionShareCentral = "anyRegionShareCentral",
    noBuildingEE = "noBuildingEE",
    vpNotHighestPlayer = "vpNotHighestPlayer",
    highestVpPlayer = "highestVpPlayer",
    aesLowest = "aesLowest",
    aesHighest = "aesHighest",
    industryLowest = "industryLowest",
    handToAnyPlayer = "handToAnyPlayer",
    industryOrAestheticsBreakthrough = "industryOrAestheticsBreakthrough",
    peek = "peek",
    minHandCountPlayers = "minHandCountPlayers",
    everyOtherCompany = "everyOtherCompany",
    everyPlayer = "everyPlayer",
    levelAndMarkLowestPlayer = "levelAndMarkLowestPlayer",
    industryHighest = "industryHighest",
    noStudio = "noStudio",
    studio = "studio",
    step = "step",
    discardNormalOrLegend = "discardNormalOrLegend",
    discardLegend = "discardLegend",
    discardAesthetics = "discardAesthetics",
    discardIndustry = "discardIndustry",
    refactor = "refactor",
    archive = "archive",
    discard = "discard",
    choice = "choice",
    update = "update",
    comment = "comment",
    pay = "pay",
    optional = "optional",
    industryOrAestheticsLevelUp = "industryOrAestheticsLevelUp",
    archiveToEEBuildingVP = "archiveToEEBuildingVP",
}

export enum BuildingType {
    cinema = "cinema",
    studio = "studio",
}

export enum VictoryType {
    othersConceded = "othersConceded",
    threeNAChampionAutoWin = "threeNAChampionAutoWin",
    championCountAutoWin = "championCountAutoWin",
    finalScoring = "finalScoring",
}

export enum MoveNames {
    setupGameMode = "setupGameMode",
    requestEndTurn = "requestEndTurn",
    showBoardStatus = "showBoardStatus",
    chooseEffect = "chooseEffect",
    chooseEvent = "chooseEvent",
    chooseHand = "chooseHand",
    chooseRegion = "chooseRegion",
    updateSlot = "updateSlot",
    payAdditionalCost = "payAdditionalCost",
    changePlayerSetting = "changePlayerSetting",
    drawCard = "drawCard",
    buyCard = "buyCard",
    showCompetitionResult = "showCompetitionResult",
    peek = "peek",
    concede = "concede",
    playCard = "playCard",
    competitionCard = "competitionCard",
    breakthrough = "breakthrough",
    comment = "comment",
}

export enum SimpleEffectNames {
    shareToVp = "shareToVp",
    none = "none",
    "skipBreakthrough" = "skipBreakthrough",
    "loseVpForEachHand" = "loseVpForEachHand",
    aestheticsToVp = "aestheticsToVp",
    industryToVp = "industryToVp",
    resFromIndustry = "resFromIndustry",
    enableHollywood = "enableHollywood",
    enableBollywood = "enableBollywood",
    loseVp = "loseVp",
    loseShareNA = "loseShareNA",
    shareNA = "shareNA",
    loseShareWE = "loseShareWE",
    shareWE = "shareWE",
    loseShareEE = "loseShareEE",
    shareEE = "shareEE",
    loseShareASIA = "loseShareASIA",
    shareASIA = "shareASIA",
    deposit = "deposit",
    res = "res",
    vp = "vp",
    addVp = "addVp",
    addExtraVp = "addExtraVp",
    draw = "draw",
    buy = "buy",
    buyCardToHand = "buyCardToHand",
    aestheticsLevelUp = "aestheticsLevelUp",
    industryLevelUp = "industryLevelUp",
    industryAward = "industryAward",
    aesAward = "aesAward",

}

export enum ScoringEffectNames {
    threeCards = "threeCards",
    aesClassic = "aesClassic",
    northAmericaFilm = "northAmericaFilm",
    asiaFilm = "asiaFilm",
    industryNormalOrLegend = "industryNormalOrLegend",
    westEuropeCard = "westEuropeCard",
    eastEuropeFilm = "eastEuropeFilm",
    industryLevel = "industryLevel",
    aestheticsLevel = "aestheticsLevel",
    personCard = "personCard",
    allNoStudioPlayer = "allNoStudioPlayer",
}

export enum NoExecutorEffectNames {
    onYourComment = "onYourComment",
    playedCardInTurnEffect = "playedCardInTurnEffect",
    doNotLoseVpAfterCompetition = "doNotLoseVpAfterCompetition",
    NewYorkSchool = "NewYorkSchool",
    obtainNormalOrLegendFilm = "obtainNormalOrLegendFilm",
    afterBreakthrough = "afterBreakthrough",
    buyNoneEEFilm = "buyNoneEEFilm",
    extraVp = "extraVp",
    inventionEraBreakthroughPrevent = "inventionEraBreakthroughPrevent",
    searchAndArchive = "searchAndArchive",
    deductRes = "deductRes",
    buyAesthetics = "buyAesthetics",
    extraEffect = "extraEffect",
    loseVpRespond = "loseVpRespond",
    othersBuySchool = "othersBuySchool",
    turnStart = "turnStart",

}

export enum EventCardID {
    "E01" = "E01",
    "E02" = "E02",
    "E03" = "E03",
    "E04" = "E04",
    "E05" = "E05",
    "E06" = "E06",
    "E07" = "E07",
    "E08" = "E08",
    "E09" = "E09",
    "E10" = "E10",
    "E11" = "E11",
    "E12" = "E12",
    "E13" = "E13",
    "E14" = "E14",
}

export enum BasicCardID {
    "B01" = "B01",
    "B02" = "B02",
    "B03" = "B03",
    "B04" = "B04",
    "B05" = "B05",
    "B06" = "B06",
    "B07" = "B07",
}

export interface IEventCard extends ICard {
    era: IEra,
    effect: any,
}

export interface IPersonCard extends INormalOrLegendCard {
    readonly type: CardType.P,
}

export interface ICost {
    res: number,
    industry: number,
    aesthetics: number,
}

export interface IScoreCard extends ICard {
    era: IEra,
    region: Region,
}

export interface IPlayerShare {
    0: number,
    1: number,
    2: number,
    3: number,
}

export interface Champion {
    era: IEra,
    region: Region,
}

export enum MainAction {
    play,
    breakthrough,
    buyCard,
    drawCard,
    scoring,
}

export interface IPubInfo {
    finalScoring: {
        card: number,
        building: number,
        industryAward: number,
        aestheticsAward: number,
        archive: number,
        events: number,
        total: number,
    },
    newHollyWoodUsed: boolean,
    discardInSettle: boolean,
    scoreEvents: EventCardID[],
    vpAward: {
        v60: boolean,
        v90: boolean,
        v120: boolean,
        v150: boolean,
    },
    champions: Champion[],
    building: {
        cinemaBuilt: boolean,
        studioBuilt: boolean,
    }
    action: number,
    deposit: number,
    resource: number,
    handSize: number,
    archive: CardID[],
    allCards: CardID[],
    discard: CardID[],
    revealedHand: CardID[],
    playedCardInTurn: CardID[],
    industry: number,
    aesthetics: number,
    school: SchoolCardID | null,
    vp: number,
    shares: IPlayerShare,
    tempStudios: Region[],
    respondMark: {
        tempStudioRespond: boolean,
        eventRespond: boolean,
    }
}

export interface IPrivateInfo {
    classicFilmAutoMove: ClassicFilmAutoMoveMode,
    endTurnEffectExecuted: boolean,
    hand: CardID[],
    handSize: number,
    cardsToPeek: CardID[],
    competitionCards: CardID[],
    deckEmpty: boolean,
}

export interface IBuildingSlot {
    region: Region,
    building: BuildingType | null,
    activated: boolean,
    owner: PlayerID,
}

export interface IRegionInfo {
    completedModernScoring: boolean,
    era: IEra,
    buildings: IBuildingSlot[],
    share: number,
    legend: ICardSlot,
    legendDeckLength: number,
    normal: ICardSlot[],
    normalDeckLength: number,
}

export interface IRegionPrivate {
    legendDeck: ClassicCardID[],
    normalDeck: ClassicCardID[],
}


export enum ScoreCardID {
    'V111' = 'V111',
    'V112' = 'V112',
    'V113' = 'V113',
    'V121' = 'V121',
    'V122' = 'V122',
    'V123' = 'V123',
    'V131' = 'V131',
    'V132' = 'V132',
    'V211' = 'V211',
    'V212' = 'V212',
    'V213' = 'V213',
    'V221' = 'V221',
    'V222' = 'V222',
    'V223' = 'V223',
    'V231' = 'V231',
    'V232' = 'V232',
    'V241' = 'V241',
    'V242' = 'V242',
    'V243' = 'V243',
    'V311' = 'V311',
    'V312' = 'V312',
    'V313' = 'V313',
    'V321' = 'V321',
    'V322' = 'V322',
    'V323' = 'V323',
    'V331' = 'V331',
    'V332' = 'V332',
    'V333' = 'V333',
    'V341' = 'V341',
    'V342' = 'V342',
    'V343' = 'V343',
}

export const SimpleRuleNumPlayers = 2;

export enum SchoolCardID {
    'S1203' = 'S1203',
    'S1204' = 'S1204',
    'S1301' = 'S1301',
    'S1303' = 'S1303',
    'S2101' = 'S2101',
    'S2104' = 'S2104',
    'S2201' = 'S2201',
    'S2204' = 'S2204',
    'S2301' = 'S2301',
    'S3101' = 'S3101',
    'S3105' = 'S3105',
    'S3201' = 'S3201',
    'S3204' = 'S3204',
}

export enum PersonCardID {
    'P1101' = 'P1101',
    'P1102' = 'P1102',
    'P1201' = 'P1201',
    'P1202' = 'P1202',
    'P1302' = 'P1302',
    'P2102' = 'P2102',
    'P2103' = 'P2103',
    'P2105' = 'P2105',
    'P2202' = 'P2202',
    'P2203' = 'P2203',
    'P2205' = 'P2205',
    'P2302' = 'P2302',
    'P2401' = 'P2401',
    'P2402' = 'P2402',
    'P3102' = 'P3102',
    'P3106' = 'P3106',
    'P3107' = 'P3107',
    'P3202' = 'P3202',
    'P3203' = 'P3203',
    'P3301' = 'P3301',
    'P3302' = 'P3302',
    'P3401' = 'P3401',
    'P3402' = 'P3402',
    'P3403' = 'P3403',
}

export enum FilmCardID {
    'F1103' = 'F1103',
    'F1104' = 'F1104',
    'F1105' = 'F1105',
    'F1106' = 'F1106',
    'F1107' = 'F1107',
    'F1108' = 'F1108',
    'F1109' = 'F1109',
    'F1110' = 'F1110',
    'F1205' = 'F1205',
    'F1206' = 'F1206',
    'F1207' = 'F1207',
    'F1208' = 'F1208',
    'F1209' = 'F1209',
    'F1210' = 'F1210',
    'F1211' = 'F1211',
    'F1304' = 'F1304',
    'F1305' = 'F1305',
    'F1306' = 'F1306',
    'F1307' = 'F1307',
    'F2106' = 'F2106',
    'F2107' = 'F2107',
    'F2108' = 'F2108',
    'F2109' = 'F2109',
    'F2110' = 'F2110',
    'F2111' = 'F2111',
    'F2112' = 'F2112',
    'F2113' = 'F2113',
    'F2114' = 'F2114',
    'F2206' = 'F2206',
    'F2207' = 'F2207',
    'F2208' = 'F2208',
    'F2209' = 'F2209',
    'F2210' = 'F2210',
    'F2211' = 'F2211',
    'F2212' = 'F2212',
    'F2213' = 'F2213',
    'F2214' = 'F2214',
    'F2303' = 'F2303',
    'F2304' = 'F2304',
    'F2305' = 'F2305',
    'F2306' = 'F2306',
    'F2307' = 'F2307',
    'F2308' = 'F2308',
    'F2309' = 'F2309',
    'F2403' = 'F2403',
    'F2404' = 'F2404',
    'F2405' = 'F2405',
    'F2406' = 'F2406',
    'F2407' = 'F2407',
    'F2408' = 'F2408',
    'F2409' = 'F2409',
    'F2410' = 'F2410',
    'F3103' = 'F3103',
    'F3104' = 'F3104',
    'F3108' = 'F3108',
    'F3109' = 'F3109',
    'F3110' = 'F3110',
    'F3111' = 'F3111',
    'F3112' = 'F3112',
    'F3113' = 'F3113',
    'F3114' = 'F3114',
    'F3115' = 'F3115',
    'F3116' = 'F3116',
    'F3205' = 'F3205',
    'F3206' = 'F3206',
    'F3207' = 'F3207',
    'F3208' = 'F3208',
    'F3209' = 'F3209',
    'F3210' = 'F3210',
    'F3211' = 'F3211',
    'F3212' = 'F3212',
    'F3213' = 'F3213',
    'F3303' = 'F3303',
    'F3304' = 'F3304',
    'F3305' = 'F3305',
    'F3306' = 'F3306',
    'F3307' = 'F3307',
    'F3308' = 'F3308',
    'F3309' = 'F3309',
    'F3310' = 'F3310',
    'F3311' = 'F3311',
    'F3312' = 'F3312',
    'F3404' = 'F3404',
    'F3405' = 'F3405',
    'F3406' = 'F3406',
    'F3407' = 'F3407',
    'F3408' = 'F3408',
    'F3409' = 'F3409',
    'F3410' = 'F3410',
    'F3411' = 'F3411',
    'F3412' = 'F3412',
    'F3413' = 'F3413',
    'F3414' = 'F3414',
}

export const AllClassicCards = {
    ...SchoolCardID,
    ...PersonCardID,
    ...FilmCardID
}

export type ClassicCardID = SchoolCardID | PersonCardID | FilmCardID


export type ValidRegion = Region.NA | Region.WE | Region.EE | Region.ASIA;
export const valid_regions: ValidRegion[] = [Region.NA, Region.WE, Region.EE, Region.ASIA];

export const TwoPlayerCardCount = {
    0: {school: 3, film: 11},
    1: {school: 3, film: 18},
    2: {school: 2, film: 12},
}

export const ShareOnBoard = {
    0: [6, 9, 12],
    1: [6, 9, 10],
    2: [4, 6, 8],
    3: [0, 6, 10],
}
export const LegendCardCountInUse = {
    0: [1, 2, 3],
    1: [1, 2, 2],
    2: [1, 1, 2],
    3: [0, 1, 2],
}
export const NormalCardCountInUse = {
    0: [5, 7, 9],
    1: [5, 7, 8],
    2: [3, 5, 6],
    3: [0, 5, 8],
}

interface IArgFilmCard {
    era: IEra,
    region: Region,
    name: string,
    cardId: CardID,
    cost: ICost,
    vp: number,
    category: CardCategory,
    industry: number,
    aesthetics: number,
}

interface IArgEvent {
    name: string,
    id: EventCardID,
    effect: any,
    era: IEra,
}

export function filmCard(arg: IArgFilmCard
): IFilmCard {
    return {
        cost: arg.cost,
        aesthetics: arg.aesthetics,
        cardId: arg.cardId,
        category: arg.category,
        industry: arg.industry,
        name: arg.name,
        type: CardType.F, era: arg.era, region: arg.region,
        vp: arg.vp
    }
}

export function personCard(arg: IArgFilmCard): IPersonCard {
    return {
        type: CardType.P, era: arg.era, region: arg.region,
        industry: arg.industry,
        vp: arg.vp,
        cost: arg.cost,
        name: arg.name,
        cardId: arg.cardId,
        category: arg.category,
        aesthetics: arg.aesthetics
    }
}

export function schoolCard(arg: IArgFilmCard): ISchoolCard {
    return {
        era: arg.era, region: arg.region,
        type: CardType.S,
        industry: arg.industry,
        vp: arg.vp,
        cost: arg.cost,
        name: arg.name,
        cardId: arg.cardId,
        category: arg.category,
        aesthetics: arg.aesthetics
    }
}

export function eventCard(arg: IArgEvent): IEventCard {
    return {
        region: Region.NONE,
        cost: cost(0, 0, 0),
        category: CardCategory.BASIC,
        type: CardType.E,
        era: arg.era,
        name: arg.name,
        effect: arg.effect,
        cardId: arg.id
    }
}

const NoneBasicCards = {
    "P1101": personCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "D.W.Griffith",
        cardId: PersonCardID.P1101,
        cost: cost(5, 0, 2),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P1102": personCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "Thomas Edison",
        cardId: PersonCardID.P1102,
        cost: cost(5, 2, 0),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F1103": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "Intolerance",
        cardId: FilmCardID.F1103,
        cost: cost(4, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1104": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "The Great Train Robbery",
        cardId: FilmCardID.F1104,
        cost: cost(4, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1105": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "The Jazz Singer",
        cardId: FilmCardID.F1105,
        cost: cost(3, 2, 0),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1106": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "The General",
        cardId: FilmCardID.F1106,
        cost: cost(3, 1, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F1107": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "The Gold Rush",
        cardId: FilmCardID.F1107,
        cost: cost(2, 0, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F1108": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "Nanook of the North",
        cardId: FilmCardID.F1108,
        cost: cost(2, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F1109": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "King Kong",
        cardId: FilmCardID.F1109,
        cost: cost(3, 3, 0),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1110": filmCard({
        era: IEra.ONE,
        region: Region.NA,
        name: "Greed",
        cardId: FilmCardID.F1110,
        cost: cost(0, 0, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "P1201": personCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "Georges Méliès",
        cardId: PersonCardID.P1201,
        cost: cost(6, 1, 1),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P1202": personCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "Lumière Brothers",
        cardId: PersonCardID.P1202,
        cost: cost(5, 2, 0),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "S1203": schoolCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "Expressionism",
        cardId: SchoolCardID.S1203,
        cost: cost(4, 0, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "S1204": schoolCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "Swedish School",
        cardId: SchoolCardID.S1204,
        cost: cost(4, 2, 2),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1205": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "Nosferatu",
        cardId: FilmCardID.F1205,
        cost: cost(2, 1, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F1206": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "The Passion of the Joan of Arc",
        cardId: FilmCardID.F1206,
        cost: cost(2, 0, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F1207": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "A Trip to the Moon",
        cardId: FilmCardID.F1207,
        cost: cost(4, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1208": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "Fantomas",
        cardId: FilmCardID.F1208,
        cost: cost(3, 2, 2),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F1209": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "The Phantom Carriage",
        cardId: FilmCardID.F1209,
        cost: cost(2, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1210": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "Existing the Factory",
        cardId: FilmCardID.F1210,
        cost: cost(3, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F1211": filmCard({
        era: IEra.ONE,
        region: Region.WE,
        name: "The Assassination of the Duke of Guise",
        cardId: FilmCardID.F1211,
        cost: cost(3, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "S1301": schoolCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "Montage School",
        cardId: SchoolCardID.S1301,
        cost: cost(4, 1, 3),
        vp: 4,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 1,
    }),
    "P1302": personCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "Sergei M. Eisenstein",
        cardId: PersonCardID.P1302,
        cost: cost(5, 0, 2),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "S1303": schoolCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "Kino Eye",
        cardId: SchoolCardID.S1303,
        cost: cost(5, 1, 1),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F1304": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "Mother",
        cardId: FilmCardID.F1304,
        cost: cost(3, 0, 2),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F1305": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "Battleship Potemkin",
        cardId: FilmCardID.F1305,
        cost: cost(3, 1, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F1306": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "Man with a Movie Camera",
        cardId: FilmCardID.F1306,
        cost: cost(3, 1, 0),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F1307": filmCard({
        era: IEra.ONE,
        region: Region.EE,
        name: "Father Sergius",
        cardId: FilmCardID.F1307,
        cost: cost(3, 0, 0),
        vp: 1,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "S2101": schoolCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Classic Hollywood",
        cardId: SchoolCardID.S2101,
        cost: cost(7, 6, 2),
        vp: 8,
        category: CardCategory.LEGEND,
        industry: 2,
        aesthetics: 0,
    }),
    "P2102": personCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "John Ford",
        cardId: PersonCardID.P2102,
        cost: cost(8, 5, 1),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P2103": personCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Alfred Hitchcock",
        cardId: PersonCardID.P2103,
        cost: cost(8, 4, 2),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "S2104": schoolCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Film Noir",
        cardId: SchoolCardID.S2104,
        cost: cost(6, 4, 2),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "P2105": personCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Orson Welles",
        cardId: PersonCardID.P2105,
        cost: cost(7, 0, 4),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F2106": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Gone With the Wind",
        cardId: FilmCardID.F2106,
        cost: cost(7, 6, 0),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F2107": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Stagecoach",
        cardId: FilmCardID.F2107,
        cost: cost(5, 5, 1),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2108": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Singin' in the Rain",
        cardId: FilmCardID.F2108,
        cost: cost(5, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2109": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Citizen Kane",
        cardId: FilmCardID.F2109,
        cost: cost(7, 0, 3),
        vp: 2,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F2110": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "White Heat",
        cardId: FilmCardID.F2110,
        cost: cost(6, 2, 0),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2111": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Sunset Blvid",
        cardId: FilmCardID.F2111,
        cost: cost(4, 3, 3),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2112": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Ben-hur",
        cardId: FilmCardID.F2112,
        cost: cost(6, 6, 0),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F2113": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "The Maltese Falcon",
        cardId: FilmCardID.F2113,
        cost: cost(5, 3, 1),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2114": filmCard({
        era: IEra.TWO,
        region: Region.NA,
        name: "Vertigo",
        cardId: FilmCardID.F2114,
        cost: cost(4, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "S2201": schoolCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "Neorealism",
        cardId: SchoolCardID.S2201,
        cost: cost(8, 0, 6),
        vp: 8,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 1,
    }),
    "P2202": personCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "Federico Fellini",
        cardId: PersonCardID.P2202,
        cost: cost(8, 1, 5),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P2203": personCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "David Lean",
        cardId: PersonCardID.P2203,
        cost: cost(7, 5, 3),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "S2204": schoolCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "Poetic Realism",
        cardId: SchoolCardID.S2204,
        cost: cost(7, 2, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "P2205": personCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "Jean Renoir",
        cardId: PersonCardID.P2205,
        cost: cost(7, 0, 4),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F2206": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "The Rules of the Game",
        cardId: FilmCardID.F2206,
        cost: cost(6, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2207": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "The Bicycle Thieves",
        cardId: FilmCardID.F2207,
        cost: cost(8, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2208": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "M",
        cardId: FilmCardID.F2208,
        cost: cost(6, 4, 0),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2209": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "The Road",
        cardId: FilmCardID.F2209,
        cost: cost(5, 1, 5),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2210": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "Diary of a Country Priest",
        cardId: FilmCardID.F2210,
        cost: cost(5, 0, 6),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2211": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "Napoleon",
        cardId: FilmCardID.F2211,
        cost: cost(4, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2212": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "Daybreak",
        cardId: FilmCardID.F2212,
        cost: cost(4, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2213": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "The Wages of Fear",
        cardId: FilmCardID.F2213,
        cost: cost(7, 1, 1),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2214": filmCard({
        era: IEra.TWO,
        region: Region.WE,
        name: "Lawrence of Arabia",
        cardId: FilmCardID.F2214,
        cost: cost(5, 5, 3),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "S2301": schoolCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "Socialist Realism",
        cardId: SchoolCardID.S2301,
        cost: cost(8, 4, 4),
        vp: 6,
        category: CardCategory.LEGEND,
        industry: 1,
        aesthetics: 1,
    }),
    "P2302": personCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "Mikhail Kalatozov",
        cardId: PersonCardID.P2302,
        cost: cost(8, 3, 3),
        vp: 5,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F2303": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "Chapaev",
        cardId: FilmCardID.F2303,
        cost: cost(7, 1, 1),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2304": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "Ballad of a Solider",
        cardId: FilmCardID.F2304,
        cost: cost(6, 2, 5),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F2305": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "The Cranes are Flying",
        cardId: FilmCardID.F2305,
        cost: cost(6, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2306": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "Canal",
        cardId: FilmCardID.F2306,
        cost: cost(7, 3, 2),
        vp: 5,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2307": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "Shadows of Forgotten Ancestors",
        cardId: FilmCardID.F2307,
        cost: cost(4, 0, 5),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F2308": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "Quiet Flows the Don",
        cardId: FilmCardID.F2308,
        cost: cost(6, 4, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2309": filmCard({
        era: IEra.TWO,
        region: Region.EE,
        name: "Earth",
        cardId: FilmCardID.F2309,
        cost: cost(6, 0, 3),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "P2401": personCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "Akira Kurosawa",
        cardId: PersonCardID.P2401,
        cost: cost(8, 3, 3),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P2402": personCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "Chusheng Cai",
        cardId: PersonCardID.P2402,
        cost: cost(6, 4, 4),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F2403": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "Spring in a small town",
        cardId: FilmCardID.F2403,
        cost: cost(6, 0, 6),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2404": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "The Spring River Flows East",
        cardId: FilmCardID.F2404,
        cost: cost(7, 2, 2),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2405": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "Alam Ara",
        cardId: FilmCardID.F2405,
        cost: cost(6, 1, 1),
        vp: 3,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F2406": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "Seven Samurai",
        cardId: FilmCardID.F2406,
        cost: cost(6, 4, 0),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2407": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "Pather Panchali",
        cardId: FilmCardID.F2407,
        cost: cost(4, 3, 5),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F2408": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "The Goddess",
        cardId: FilmCardID.F2408,
        cost: cost(5, 0, 4),
        vp: 6,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F2409": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "Godzilla",
        cardId: FilmCardID.F2409,
        cost: cost(6, 5, 0),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F2410": filmCard({
        era: IEra.TWO,
        region: Region.ASIA,
        name: "This Life of Mine",
        cardId: FilmCardID.F2410,
        cost: cost(5, 2, 0),
        vp: 4,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "S3101": schoolCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "New Hollywood",
        cardId: SchoolCardID.S3101,
        cost: cost(10, 10, 2),
        vp: 13,
        category: CardCategory.LEGEND,
        industry: 2,
        aesthetics: 2,
    }),
    "P3102": personCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "Steven Spielberg",
        cardId: PersonCardID.P3102,
        cost: cost(10, 10, 5),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F3103": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "The Godfather",
        cardId: FilmCardID.F3103,
        cost: cost(10, 8, 8),
        vp: 11,
        category: CardCategory.LEGEND,
        industry: 1,
        aesthetics: 2,
    }),
    "F3104": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "Star War",
        cardId: FilmCardID.F3104,
        cost: cost(9, 10, 0),
        vp: 13,
        category: CardCategory.LEGEND,
        industry: 3,
        aesthetics: 0,
    }),
    "S3105": schoolCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "New York School",
        cardId: SchoolCardID.S3105,
        cost: cost(9, 4, 4),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "P3106": personCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "Martin Scorsese",
        cardId: PersonCardID.P3106,
        cost: cost(10, 5, 5),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "P3107": personCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "Roger Corman",
        cardId: PersonCardID.P3107,
        cost: cost(10, 6, 0),
        vp: 0,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F3108": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "Titanic",
        cardId: FilmCardID.F3108,
        cost: cost(9, 12, 0),
        vp: 15,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F3109": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "2001: A Space Odyssey",
        cardId: FilmCardID.F3109,
        cost: cost(8, 7, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 2,
    }),
    "F3110": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "The Exorcist",
        cardId: FilmCardID.F3110,
        cost: cost(8, 8, 2),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3111": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "Bonnie and Clyde",
        cardId: FilmCardID.F3111,
        cost: cost(10, 5, 4),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3112": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "Taxi Driver",
        cardId: FilmCardID.F3112,
        cost: cost(8, 5, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F3113": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "Raiders of the Lost Ark",
        cardId: FilmCardID.F3113,
        cost: cost(9, 10, 0),
        vp: 13,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F3114": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "The Longest Yard",
        cardId: FilmCardID.F3114,
        cost: cost(9, 6, 0),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3115": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "Butch Cassidy and the Sundance Kid",
        cardId: FilmCardID.F3115,
        cost: cost(8, 6, 2),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3116": filmCard({
        era: IEra.THREE,
        region: Region.NA,
        name: "The Shining",
        cardId: FilmCardID.F3116,
        cost: cost(8, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "S3201": schoolCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "New Wave",
        cardId: SchoolCardID.S3201,
        cost: cost(9, 4, 10),
        vp: 3,
        category: CardCategory.LEGEND,
        industry: 1,
        aesthetics: 3,
    }),
    "P3202": personCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Francois Truffaut",
        cardId: PersonCardID.P3202,
        cost: cost(10, 5, 7),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P3203": personCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Ingmar Bergman",
        cardId: PersonCardID.P3203,
        cost: cost(10, 0, 10),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "S3204": schoolCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Left Bank Group",
        cardId: SchoolCardID.S3204,
        cost: cost(7, 0, 8),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 3,
    }),
    "F3205": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "The Godsun",
        cardId: FilmCardID.F3205,
        cost: cost(8, 6, 8),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3206": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Fitzcarraldo",
        cardId: FilmCardID.F3206,
        cost: cost(8, 8, 2),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3207": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Last Year at Marienbad",
        cardId: FilmCardID.F3207,
        cost: cost(9, 0, 10),
        vp: 13,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 3,
    }),
    "F3208": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Eight and a Half",
        cardId: FilmCardID.F3208,
        cost: cost(8, 0, 12),
        vp: 15,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 3,
    }),
    "F3209": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Jules and Jim",
        cardId: FilmCardID.F3209,
        cost: cost(7, 4, 9),
        vp: 15,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3210": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Golden Eye",
        cardId: FilmCardID.F3210,
        cost: cost(9, 9, 0),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F3211": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "The Adventure",
        cardId: FilmCardID.F3211,
        cost: cost(8, 0, 9),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3212": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Persona",
        cardId: FilmCardID.F3212,
        cost: cost(6, 3, 9),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F3213": filmCard({
        era: IEra.THREE,
        region: Region.WE,
        name: "Kes",
        cardId: FilmCardID.F3213,
        cost: cost(7, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "P3301": personCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "Andrei Tarkovsky",
        cardId: PersonCardID.P3301,
        cost: cost(9, 4, 10),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P3302": personCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "Sergi Bondarchuk",
        cardId: PersonCardID.P3302,
        cost: cost(9, 10, 4),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F3303": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "Three Colors: Blue",
        cardId: FilmCardID.F3303,
        cost: cost(9, 0, 11),
        vp: 14,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 2,
    }),
    "F3304": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "War and Peace",
        cardId: FilmCardID.F3304,
        cost: cost(8, 10, 4),
        vp: 13,
        category: CardCategory.NORMAL,
        industry: 2,
        aesthetics: 0,
    }),
    "F3305": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "Underground",
        cardId: FilmCardID.F3305,
        cost: cost(9, 4, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3306": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "Most",
        cardId: FilmCardID.F3306,
        cost: cost(8, 9, 3),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3307": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "Office Romance",
        cardId: FilmCardID.F3307,
        cost: cost(9, 3, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F3308": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "The Red and the White",
        cardId: FilmCardID.F3308,
        cost: cost(8, 3, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3309": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "Solaris",
        cardId: FilmCardID.F3309,
        cost: cost(6, 4, 8),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3310": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "Triumph Over Violence",
        cardId: FilmCardID.F3310,
        cost: cost(8, 3, 5),
        vp: 8,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3311": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "The Diamond Arm",
        cardId: FilmCardID.F3311,
        cost: cost(7, 4, 4),
        vp: 7,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3312": filmCard({
        era: IEra.THREE,
        region: Region.EE,
        name: "Marketa Lazarova",
        cardId: FilmCardID.F3312,
        cost: cost(9, 7, 4),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "P3401": personCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Zhang Yimou",
        cardId: PersonCardID.P3401,
        cost: cost(10, 5, 5),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P3402": personCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Kar Wai Wong",
        cardId: PersonCardID.P3402,
        cost: cost(9, 4, 7),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "P3403": personCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Abbas Kiarostami",
        cardId: PersonCardID.P3403,
        cost: cost(10, 0, 9),
        vp: 0,
        category: CardCategory.LEGEND,
        industry: 0,
        aesthetics: 0,
    }),
    "F3404": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Farwell My Concubine",
        cardId: FilmCardID.F3404,
        cost: cost(8, 4, 9),
        vp: 12,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 2,
    }),
    "F3405": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Chungking Express",
        cardId: FilmCardID.F3405,
        cost: cost(8, 4, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3406": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "A Better Tomorrow",
        cardId: FilmCardID.F3406,
        cost: cost(8, 8, 3),
        vp: 11,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3407": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Sholay",
        cardId: FilmCardID.F3407,
        cost: cost(8, 6, 2),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 0,
    }),
    "F3408": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Red Sorghum",
        cardId: FilmCardID.F3408,
        cost: cost(7, 4, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 1,
        aesthetics: 1,
    }),
    "F3409": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Hibiscus Town",
        cardId: FilmCardID.F3409,
        cost: cost(8, 2, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3410": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "A Touch of Zen",
        cardId: FilmCardID.F3410,
        cost: cost(6, 4, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3411": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Seopyeonje",
        cardId: FilmCardID.F3411,
        cost: cost(7, 3, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3412": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "The Scent of Green Papaya",
        cardId: FilmCardID.F3412,
        cost: cost(7, 0, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 0,
    }),
    "F3413": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "The Boys from Fengkuei",
        cardId: FilmCardID.F3413,
        cost: cost(8, 0, 6),
        vp: 9,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
    "F3414": filmCard({
        era: IEra.THREE,
        region: Region.ASIA,
        name: "Taste of Cherry",
        cardId: FilmCardID.F3414,
        cost: cost(7, 0, 7),
        vp: 10,
        category: CardCategory.NORMAL,
        industry: 0,
        aesthetics: 1,
    }),
}

const E01: IEventCard = eventCard({
    era: IEra.ONE,
    name: "",
    effect: {}, id: EventCardID.E01
})
const E02: IEventCard = eventCard({
    era: IEra.ONE,
    name: "Edison Litigation",
    effect: {}, id: EventCardID.E02
})
const E03: IEventCard = eventCard({
    era: IEra.ONE,
    name: "Avant-garde",
    effect: {}, id: EventCardID.E03
})
const E04: IEventCard = eventCard({
    era: IEra.ONE,
    name: "Academy Award",
    effect: {}, id: EventCardID.E04
})
const E05: IEventCard = eventCard({
    era: IEra.TWO,
    name: "Paramount Judgement",
    effect: {}, id: EventCardID.E05
})
const E06: IEventCard = eventCard({
    era: IEra.TWO,
    name: "Cannes International Film  Festival",
    effect: {}, id: EventCardID.E06
})
const E07: IEventCard = eventCard({
    era: IEra.TWO,
    name: "LES CHAIERS DU CINEMA",
    effect: {}, id: EventCardID.E07
})
const E08: IEventCard = eventCard({
    era: IEra.TWO,
    name: `Khrushchev's "unfreeze"`,
    effect: {}, id: EventCardID.E08
})
const E09: IEventCard = eventCard({
    era: IEra.TWO,
    name: "Rising of Bollywood",
    effect: {}, id: EventCardID.E09
})
const E10: IEventCard = eventCard({
    era: IEra.TWO,
    name: "Dismantling of HAYS CODE",
    effect: {}, id: EventCardID.E10
})
const E11: IEventCard = eventCard({
    era: IEra.THREE,
    name: "Film Authorship",
    effect: {}, id: EventCardID.E11
})
const E12: IEventCard = eventCard({
    era: IEra.THREE,
    name: "New Wave of Film",
    effect: {}, id: EventCardID.E12
})
const E13: IEventCard = eventCard({
    era: IEra.THREE,
    name: "Globalization",
    effect: {}, id: EventCardID.E13
})
const E14: IEventCard = eventCard({
    era: IEra.THREE,
    name: "New Media",
    effect: {}, id: EventCardID.E14
})
const EVENT_CARDS = [E01, E02, E03, E04, E05, E06, E07, E08, E09, E10, E11, E12, E13, E14]
const EVENT_ERA = [[E01, E02, E03, E04,], [E05, E06, E07, E08, E09,], [E10, E11, E12, E13, E14]]
export let idToCard = new Map();
EVENT_CARDS.forEach((v: IEventCard) => {
    idToCard.set(v.cardId, v);
})
export const eventCardByEra = (era: IEra): IEventCard[] => EVENT_ERA[era];
export const eventCardById = (id: EventCardID): IEventCard[] => idToCard.get(id);

const SCORE_CARDS = {
    "V111": {
        cost: cost(0, 0, 0),
        era: IEra.ONE,
        region: Region.NA,
        name: "V111",
        cardId: "V111",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 9,
        industry: 1,
        aesthetics: 0,
    },
    "V112": {
        cost: cost(0, 0, 0),
        era: IEra.ONE,
        region: Region.NA,
        name: "V112",
        cardId: "V112",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 6,
        industry: 0,
        aesthetics: 0,
    },
    "V113": {
        cost: cost(0, 0, 0),
        era: IEra.ONE,
        region: Region.NA,
        name: "V113",
        cardId: "V113",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 3,
        vp: 3,
        industry: 0,
        aesthetics: 0,
    },
    "V121": {
        cost: cost(0, 0, 0),
        era: IEra.ONE,
        region: Region.WE,
        name: "V121",
        cardId: "V121",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 11,
        industry: 0,
        aesthetics: 1,
    },
    "V122": {
        cost: cost(0, 0, 0),
        era: IEra.ONE,
        region: Region.WE,
        name: "V122",
        cardId: "V122",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 8,
        industry: 0,
        aesthetics: 0,
    },
    "V123": {
        cost: cost(0, 0, 0),
        era: IEra.ONE,
        region: Region.WE,
        name: "V123",
        cardId: "V123",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 3,
        vp: 5,
        industry: 0,
        aesthetics: 0,
    },
    "V131": {
        cost: cost(0, 0, 0),
        era: IEra.ONE,
        region: Region.EE,
        name: "V131",
        cardId: "V131",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 6,
        industry: 0,
        aesthetics: 0,
    },
    "V132": {
        cost: cost(0, 0, 0),
        era: IEra.ONE,
        region: Region.EE,
        name: "V132",
        cardId: "V132",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 3,
        industry: 0,
        aesthetics: 0,
    },
    "V211": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.NA,
        name: "V211",
        cardId: "V211",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 14,
        industry: 1,
        aesthetics: 0,
    },
    "V212": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.NA,
        name: "V212",
        cardId: "V212",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 10,
        industry: 1,
        aesthetics: 0,
    },
    "V213": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.NA,
        name: "V213",
        cardId: "V213",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 3,
        vp: 6,
        industry: 0,
        aesthetics: 0,
    },
    "V221": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.WE,
        name: "V221",
        cardId: "V221",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 14,
        industry: 0,
        aesthetics: 1,
    },
    "V222": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.WE,
        name: "V222",
        cardId: "V222",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 10,
        industry: 0,
        aesthetics: 1,
    },
    "V223": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.WE,
        name: "V223",
        cardId: "V223",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 3,
        vp: 6,
        industry: 0,
        aesthetics: 0,
    },
    "V231": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.EE,
        name: "V231",
        cardId: "V231",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 9,
        industry: 1,
        aesthetics: 0,
    },
    "V232": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.EE,
        name: "V232",
        cardId: "V232",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 5,
        industry: 0,
        aesthetics: 0,
    },
    "V241": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.ASIA,
        name: "V241",
        cardId: "V241",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 11,
        industry: 0,
        aesthetics: 1,
    },
    "V242": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.ASIA,
        name: "V242",
        cardId: "V242",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 7,
        industry: 0,
        aesthetics: 0,
    },
    "V243": {
        cost: cost(0, 0, 0),
        era: IEra.TWO,
        region: Region.ASIA,
        name: "V243",
        cardId: "V243",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 3,
        vp: 3,
        industry: 0,
        aesthetics: 0,
    },
    "V311": {
        era: IEra.THREE,
        region: Region.NA,
        name: "V311",
        cardId: "V311",
        cost: cost(0, 0, 0),
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 20,
        industry: 1,
        aesthetics: 0,
    },
    "V312": {
        era: IEra.THREE,
        region: Region.NA,
        name: "V312",
        cardId: "V312",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 15,
        cost: cost(0, 0, 0),
        industry: 1,
        aesthetics: 0,
    },
    "V313": {
        era: IEra.THREE,
        region: Region.NA,
        name: "V313",
        cardId: "V313",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 3,
        vp: 10,
        cost: cost(0, 0, 0),
        industry: 1,
        aesthetics: 0,
    },
    "V321": {
        cost: cost(0, 0, 0),
        era: IEra.THREE,
        region: Region.WE,
        name: "V321",
        cardId: "V321",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 16,
        industry: 0,
        aesthetics: 1,
    },
    "V322": {
        era: IEra.THREE,
        region: Region.WE,
        name: "V322",
        cardId: "V322",
        cost: cost(0, 0, 0),
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 12,
        industry: 0,
        aesthetics: 1,
    },
    "V323": {
        era: IEra.THREE,
        region: Region.WE,
        name: "V323",
        cardId: "V323",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 3,
        vp: 8,
        cost: cost(0, 0, 0),
        industry: 0,
        aesthetics: 1,
    },
    "V331": {
        era: IEra.THREE,
        region: Region.EE,
        name: "V331",
        cardId: "V331",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 15,
        industry: 1,
        cost: cost(0, 0, 0),
        aesthetics: 0,
    },
    "V332": {
        cost: cost(0, 0, 0),
        era: IEra.THREE,
        region: Region.EE,
        name: "V332",
        cardId: "V332",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 10,
        industry: 1,
        aesthetics: 0,
    },
    "V333": {
        cost: cost(0, 0, 0),
        era: IEra.THREE,
        region: Region.EE,
        name: "V333",
        cardId: "V333",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 3,
        vp: 5,
        industry: 1,
        aesthetics: 0,
    },
    "V341": {
        cost: cost(0, 0, 0),
        era: IEra.THREE,
        region: Region.ASIA,
        name: "V341",
        cardId: "V341",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 1,
        vp: 16,
        industry: 0,
        aesthetics: 1,
    },
    "V342": {
        cost: cost(0, 0, 0),
        era: IEra.THREE,
        region: Region.ASIA,
        name: "V342",
        cardId: "V342",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 2,
        vp: 11,
        industry: 0,
        aesthetics: 1,
    },
    "V343": {
        cost: cost(0, 0, 0),
        era: IEra.THREE,
        region: Region.ASIA,
        name: "V343",
        cardId: "V343",
        category: CardCategory.SCORE,
        type: CardType.V,
        rank: 3,
        vp: 6,
        industry: 0,
        aesthetics: 1,
    },
}
export const scoreCardCount = (r: Region, era: IEra): number => {
    let cards = Object.entries(SCORE_CARDS)
    return cards.filter(e => e[1].region === r && e[1].era === era).length;
}
export const getScoreCard = (r: Region, era: IEra, rank: number) => {
    let cards = Object.entries(SCORE_CARDS)
    return cards.filter(e => e[1].region === r && e[1].era === era && e[1].rank === rank)[0][1];
}
export const getScoreCardByID = (id: string) => {
    // @ts-ignore
    return SCORE_CARDS[id];
}

export const B01: IBasicCard = {
    region: Region.NONE,
    aesthetics: 1, cardId: BasicCardID.B01,
    cost: cost(2, 0, 0),
    industry: 0,
    type: CardType.F,
    vp: 0,
    name: "Literary Film",
    category: CardCategory.BASIC
}
export const B02: IBasicCard = {
    region: Region.NONE,
    aesthetics: 0, cardId: BasicCardID.B02,
    cost: cost(2, 0, 0),
    industry: 1,
    type: CardType.F,
    vp: 0,
    name: "Commercial Film",
    category: CardCategory.BASIC
}
export const B03: IBasicCard = {
    aesthetics: 0, cardId: BasicCardID.B03,
    cost: cost(2, 0, 0),
    region: Region.NONE,
    industry: 0,
    type: CardType.F,
    vp: 0,
    name: "B-Movie",
    category: CardCategory.BASIC
}
export const B04: IBasicCard = {
    aesthetics: 0, cardId: BasicCardID.B04,
    cost: cost(0, 0, 0),
    industry: 0,
    type: CardType.F,
    vp: -3,
    region: Region.NONE,
    name: "Bad Film",
    category: CardCategory.BASIC
}
export const B05: IBasicCard = {
    aesthetics: 1, cardId: BasicCardID.B05,
    cost: cost(6, 1, 1),
    industry: 1,
    type: CardType.F,
    vp: 3,
    name: "Classic Film",
    category: CardCategory.BASIC,
    region: Region.NONE,
}
export const B06: IBasicCard = {
    aesthetics: 1, cardId: BasicCardID.B06,
    cost: cost(6, 1, 1),
    industry: 1,
    type: CardType.F,
    vp: 3,
    name: "Classic Film",
    category: CardCategory.BASIC,
    region: Region.NONE,
}
export const B07: IBasicCard = {
    region: Region.NONE,
    aesthetics: 0, cardId: BasicCardID.B07,
    cost: cost(0, 0, 0),
    industry: 0,
    vp: 0,
    name: "Fund",
    type: CardType.F,
    category: CardCategory.BASIC
}
const BasicCards = {
    B01: B01,
    B02: B02,
    B03: B03,
    B04: B04,
    B05: B05,
    B06: B06,
    B07: B07,
}

export function getBasicCard(id: BasicCardID): IBasicCard {
    return BasicCards[id];
}

export function getCardById(id: string): INormalOrLegendCard {
    if (id in NoneBasicCards) {
        // @ts-ignore
        return NoneBasicCards[id];
    } else {
        if (id in BasicCardID) {
            // @ts-ignore
            return getBasicCard(id as BasicCardID);
        } else {
            if (id in EventCardID) {
                return eventCardById(id as EventCardID) as unknown as INormalOrLegendCard;
            } else {
                if (id in ScoreCardID) {
                    return getScoreCardByID(id);
                } else {
                    throw new Error("No such card id " + id)
                }
            }
        }
    }
}

export function schoolCardsByEra(e: IEra) {
    let cards = Object.entries(NoneBasicCards);
    let res = cards.filter(c => c[1].era === e).filter(c => c[1].type === CardType.S)
    return res.map(c => c[1]);
}

export function filmCardsByEra(e: IEra) {
    let cards = Object.entries(NoneBasicCards);
    let res = cards.filter(c => c[1].era === e).filter(c => c[1].type === CardType.F)
    return res.map(c => c[1]);
}

export function cardsByCond(r: Region, e: IEra, isLegend: boolean = false): INormalOrLegendCard[] {
    let cards = Object.entries(NoneBasicCards);
    let res = cards.filter(c => c[1].era === e).filter(c => c[1].region === r)

    if (isLegend) {
        res = res.filter(c => c[1].category === CardCategory.LEGEND)
    } else {
        res = res.filter(c => c[1].category === CardCategory.NORMAL)
    }
    return res.map(c => c[1]);
}
