import {Client} from 'boardgame.io/client';
import {Local} from 'boardgame.io/multiplayer'
import {FilmCentenaryGame} from './Game';
import {IG} from "./types/setup";

const hasDuplicateClassicCard = (G:IG,p:number) =>{
    const validCards = [...G.pub[p].discard,...G.secretInfo.playerDecks[p],...G.player[p].hand];
    console.log(validCards)
}

const gameWithSeed = (seed: string) => ({
    ...FilmCentenaryGame,
    seed
});

it('Duplicate cards', () => {
    const spec = {
        numPlayers: 2,
        game: gameWithSeed("kgs0jz9f"),
        multiplayer: Local(),
    };

    const p0 = Client({...spec, playerID: '0'} as any) as any;
    const p1 = Client({...spec, playerID: '1'} as any) as any;
    p0.start()
    p1.start()

    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F1207","resource":4,"deposit":0,"helper":[]})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"B02","resource":2,"deposit":0,"helper":[]})
    p1.moves.playCard({"card":"B01","idx":0,"playerID":"1","res":0})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B02","idx":0,"playerID":"0","res":0})
    p0.undo()
    p0.moves.breakthrough({"card":"B02","idx":0,"playerID":"0","res":2})
    p0.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.playCard({"card":"B01","idx":0,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"B02","idx":0,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"B02","resource":2,"deposit":0,"helper":[]})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"B01","resource":2,"deposit":0,"helper":[]})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"F1207","idx":1,"playerID":"0","res":2})
    p0.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.playCard({"card":"B01","idx":0,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":2,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"B02","idx":1,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"S1303","resource":3,"deposit":0,"helper":["B02"]})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"B01","idx":0,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":3,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F1105","resource":3,"deposit":0,"helper":[]})
    p0.moves.drawCard("0")
    p0.moves.playCard({"card":"B01","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"B01","idx":0,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1105","idx":1,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"B02","idx":0,"playerID":"0","res":2})
    p0.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.drawCard("0")
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"S1204","resource":4,"deposit":0,"helper":[]})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"B01","idx":0,"playerID":"0","res":2})
    p0.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.playCard({"card":"F1105","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F1110","resource":3,"deposit":1,"helper":[]})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F1208","resource":3,"deposit":0,"helper":[]})
    p1.moves.buyCard({"buyer":"1","target":"F1107","resource":2,"deposit":0,"helper":[]})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F1209","resource":2,"deposit":0,"helper":[]})
    p0.moves.buyCard({"buyer":"0","target":"B03","resource":2,"deposit":0,"helper":[]})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F1304","resource":3,"deposit":0,"helper":[]})
    p1.moves.buyCard({"buyer":"1","target":"F1205","resource":2,"deposit":0,"helper":[]})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"F1110","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1105","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B03","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F1103","resource":4,"deposit":0,"helper":[]})
    p0.moves.buyCard({"buyer":"0","target":"B02","resource":1,"deposit":1,"helper":[]})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"F1107","idx":0,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.playCard({"card":"F1208","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F1206","resource":2,"deposit":0,"helper":[]})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F1306","resource":3,"deposit":0,"helper":[]})
    p0.moves.playCard({"card":"F1209","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F1206","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":2,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F1304","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F1208","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F1211","resource":3,"deposit":0,"helper":[]})
    p1.moves.buyCard({"buyer":"1","target":"B03","resource":2,"deposit":0,"helper":[]})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1306","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1105","idx":1,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"B02","idx":0,"playerID":"0","res":2})
    p0.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.payAdditionalCost({"res":1,"deposit":0})
    p0.moves.drawCard("0")
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.drawCard("1")
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F2213","resource":5,"deposit":0,"helper":[]})
    p1.moves.playCard({"card":"F1205","idx":0,"playerID":"1","res":0})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B03","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1110","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.undo()
    p0.undo()
    p0.moves.breakthrough({"card":"F1110","idx":1,"playerID":"0","res":2})
    p0.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1103","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"B01","resource":1,"deposit":1,"helper":[]})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":2,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":2,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"F1304","idx":1,"playerID":"1","res":2})
    p1.moves.comment({"target":"F2304","comment":"B02","p":"1"})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.payAdditionalCost({"res":1,"deposit":0})
    p1.moves.drawCard("1")
    p1.moves.playCard({"card":"F1211","idx":0,"playerID":"1","res":0})
    p1.moves.comment({"target":"S2101","comment":"B04","p":"1"})
    p1.moves.playCard({"card":"F1208","idx":0,"playerID":"1","res":0})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"B04","idx":0,"playerID":"0","res":2})
    p0.moves.breakthrough({"card":"F1306","idx":0,"playerID":"0","res":1})
    p0.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B03","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.drawCard("1")
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F2304","resource":6,"deposit":0,"helper":[]})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1209","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1103","idx":2,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"F1105","idx":0,"playerID":"0","res":2})
    p0.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.payAdditionalCost({"res":1,"deposit":0})
    p0.moves.drawCard("0")
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"F2213","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":3,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"F1206","idx":1,"playerID":"1","res":2})
    p1.moves.chooseHand({"hand":"B04","idx":0,"p":"1"})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.payAdditionalCost({"res":1,"deposit":0})
    p1.moves.breakthrough({"card":"F1205","idx":0,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.undo()
    p1.undo()
    p1.moves.drawCard("1")
    p1.moves.playCard({"card":"B03","idx":1,"playerID":"1","res":0})
    p1.undo()
    p1.undo()
    p1.moves.breakthrough({"card":"F1205","idx":0,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.payAdditionalCost({"res":0,"deposit":1})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":3,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B03","idx":1,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F2112","resource":4,"deposit":2,"helper":[]})
    p0.moves.drawCard("0")
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B03","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"B02","idx":1,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.breakthrough({"card":"F1211","idx":0,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.undo()
    p1.undo()
    p1.moves.buyCard({"buyer":"1","target":"B03","resource":2,"deposit":0,"helper":[]})
    p1.moves.playCard({"card":"F1211","idx":0,"playerID":"1","res":0})
    p1.moves.comment({"target":"F2106","comment":"B04","p":"1"})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1103","idx":2,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F1209","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"B01","idx":0,"playerID":"0","res":2})
    p0.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.drawCard("0")
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":2,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.drawCard("1")
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F2207","resource":5,"deposit":3,"helper":[]})
    p1.moves.playCard({"card":"F1208","idx":0,"playerID":"1","res":0})
    p1.moves.chooseEffect({"effect":{"e":"industryLevelUp","a":1},"idx":0,"p":"1"})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B03","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F2112","idx":0,"playerID":"0","res":0})
    p0.moves.confirmRespond("yes")
    p0.moves.chooseTarget({"target":"1","idx":0,"p":"0","targetName":"Blue"})
    p0.undo()
    p0.undo()
    p0.moves.confirmRespond("no")
    p0.moves.playCard({"card":"F1209","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"S2101","resource":8,"deposit":0,"helper":[]})
    p0.moves.drawCard("0")
    p0.moves.playCard({"card":"F1103","idx":0,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":3,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2304","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2213","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B03","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"S2201","resource":8,"deposit":1,"helper":[]})
    p1.moves.playCard({"card":"F1211","idx":0,"playerID":"1","res":0})
    p1.moves.comment({"target":"F2407","comment":"B04","p":"1"})
    p1.undo()
    p1.undo()
    p1.moves.drawCard("1")
    p1.undo()
    p1.undo()
    p1.undo()
    p1.undo()
    p1.moves.drawCard("1")
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B03","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B03","idx":1,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"S2201","resource":9,"deposit":0,"helper":[]})
    p1.moves.playCard({"card":"F1211","idx":0,"playerID":"1","res":0})
    p1.moves.comment({"target":"F2407","comment":"B04","p":"1"})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F2112","idx":2,"playerID":"0","res":0})
    p0.moves.confirmRespond("no")
    p0.undo()
    p0.moves.confirmRespond("yes")
    p0.moves.chooseTarget({"target":"1","idx":0,"p":"0","targetName":"Blue"})
    p0.undo()
    p0.undo()
    p0.moves.confirmRespond("no")
    p0.moves.playCard({"card":"B03","idx":2,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F2404","resource":7,"deposit":0,"helper":[]})
    p0.moves.playCard({"card":"F1103","idx":2,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"F1209","idx":1,"playerID":"0","res":0})
    p0.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.payAdditionalCost({"res":0,"deposit":2})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2207","idx":0,"playerID":"1","res":0})
    p1.moves.chooseEffect({"effect":{"e":"step","a":[{"e":"res","a":2},{"e":"deposit","a":1}]},"idx":0,"p":"1"})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F1208","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F2308","resource":4,"deposit":0,"helper":[]})
    p1.moves.buyCard({"buyer":"1","target":"F2307","resource":2,"deposit":0,"helper":[]})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"B04","idx":0,"playerID":"0","res":2})
    p0.moves.playCard({"card":"B03","idx":0,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"F1103","idx":0,"playerID":"0","res":2})
    p0.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.payAdditionalCost({"res":2,"deposit":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B03","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2307","idx":0,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"F1211","idx":0,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.payAdditionalCost({"res":2,"deposit":0})
    p1.moves.playCard({"card":"F2308","idx":0,"playerID":"1","res":0})
    p1.undo()
    p1.undo()
    p1.undo()
    p1.undo()
    p1.undo()
    p1.undo()
    p1.moves.playCard({"card":"F2307","idx":1,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2308","idx":2,"playerID":"1","res":0})
    p1.moves.breakthrough({"card":"F1211","idx":1,"playerID":"1","res":2})
    p1.moves.chooseEffect({"effect":{"e":"aestheticsLevelUpCost","a":1},"idx":0,"p":"1"})
    p1.moves.payAdditionalCost({"res":2,"deposit":0})
    p1.moves.breakthrough({"card":"B07","idx":0,"playerID":"1","res":2})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":1,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F2112","idx":1,"playerID":"0","res":0})
    p0.moves.confirmRespond("no")
    p0.moves.playCard({"card":"F2404","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F2107","resource":5,"deposit":0,"helper":[]})
    p0.moves.playCard({"card":"B03","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F2306","resource":7,"deposit":0,"helper":[]})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"F1208","idx":0,"playerID":"1","res":0})
    p1.undo()
    p1.moves.playCard({"card":"F2213","idx":3,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":3,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":1,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F2108","resource":3,"deposit":0,"helper":[]})
    p1.undo()
    p1.undo()
    p1.undo()
    p1.moves.buyCard({"buyer":"1","target":"F2106","resource":3,"deposit":8,"helper":[]})
    p1.moves.playCard({"card":"B03","idx":4,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2207","idx":2,"playerID":"1","res":0})
    p1.moves.chooseEffect({"effect":{"e":"breakthroughResDeduct","a":2},"idx":1,"p":"1"})
    p1.moves.chooseHand({"hand":"B07","idx":1,"p":"1"})
    p1.moves.playCard({"card":"F1208","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F2108","resource":2,"deposit":1,"helper":[]})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F2107","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F2306","idx":0,"playerID":"0","res":0})
    p0.moves.chooseHand({"hand":"B07","idx":3,"p":"0"})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"F2404","idx":1,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F2305","resource":6,"deposit":0,"helper":[]})
    p0.moves.buyCard({"buyer":"0","target":"F2211","resource":4,"deposit":0,"helper":[]})
    p0.moves.playCard({"card":"B03","idx":0,"playerID":"0","res":0})
    p0.moves.requestEndTurn("0");
    p1.moves.playCard({"card":"F2304","idx":2,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2106","idx":2,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2207","idx":3,"playerID":"1","res":0})
    p1.moves.chooseEffect({"effect":{"e":"breakthroughResDeduct","a":2},"idx":1,"p":"1"})
    p1.moves.chooseHand({"hand":"B04","idx":2,"p":"1"})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F2303","resource":5,"deposit":0,"helper":[]})
    p1.moves.buyCard({"buyer":"1","target":"F2114","resource":2,"deposit":0,"helper":[]})
    p1.moves.requestEndTurn("1");
    p1.moves.chooseEffect({"effect":{"e":"industryLevelUp","a":1},"idx":0,"p":"1"})
    p0.moves.playCard({"card":"F2305","idx":6,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.playCard({"card":"B07","idx":5,"playerID":"0","res":0})
    p0.moves.breakthrough({"card":"F2211","idx":4,"playerID":"0","res":2})
    p0.moves.comment({"target":"F2212","comment":"B04","p":"0"})
    p0.moves.chooseEffect({"effect":{"e":"aestheticsBreakthrough","a":1},"idx":1,"p":"0"})
    p0.moves.chooseEffect({"effect":{"e":"refactor","a":1},"idx":1,"p":"0"})
    p0.moves.chooseHand({"hand":"F2107","idx":3,"p":"0"})
    p0.moves.chooseEffect({"effect":{"e":"industryLevelUpCost","a":1},"idx":0,"p":"0"})
    p0.moves.payAdditionalCost({"res":2,"deposit":0})
    p0.moves.playCard({"card":"F2112","idx":2,"playerID":"0","res":0})
    p0.moves.confirmRespond("no")
    p0.moves.playCard({"card":"B07","idx":0,"playerID":"0","res":0})
    p0.moves.buyCard({"buyer":"0","target":"F2309","resource":5,"deposit":1,"helper":[]})
    p0.moves.requestEndTurn("0");
    p0.moves.chooseEffect({"effect":{"e":"aestheticsLevelUp","a":1},"idx":1,"p":"0"})
    p1.moves.playCard({"card":"F2108","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2307","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2213","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"F2308","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F2208","resource":6,"deposit":0,"helper":[]})
    p1.moves.playCard({"card":"B07","idx":0,"playerID":"1","res":0})
    p1.moves.playCard({"card":"B03","idx":0,"playerID":"1","res":0})
    p1.moves.buyCard({"buyer":"1","target":"F2212","resource":2,"deposit":0,"helper":[]})
    p1.moves.playCard({"card":"F1208","idx":0,"playerID":"1","res":0})
    p1.moves.requestEndTurn("1");
    p0.moves.playCard({"card":"F2404","idx":2,"playerID":"0","res":0})
    hasDuplicateClassicCard(p0.store.getState().G,0);
    p0.moves.playCard({"card":"F2112","idx":6,"playerID":"0","res":0})
    p0.moves.confirmRespond("no")

    p0.stop()
    p1.stop()
});
it('Nanook', () => {
    const spec = {
        numPlayers: 2,
        game: gameWithSeed("kg7q3639"),
        multiplayer: Local(),
    };

    const p0 = Client({...spec, playerID: '0'} as any) as any;
    const p1 = Client({...spec, playerID: '1'} as any) as any;
    p0.start()
    p1.start()


    p0.stop()
    p1.stop()
})
it('Sergei M. Eisenstein', () => {
    const spec = {
        numPlayers: 3,
        game: gameWithSeed("kggnpxwo"),
        multiplayer: Local(),
    };

    const p0 = Client({...spec, playerID: '0'} as any) as any;
    const p1 = Client({...spec, playerID: '1'} as any) as any;
    const p2 = Client({...spec, playerID: '2'} as any) as any;

    p0.start();
    p1.start();
    p2.start();

    p0.stop();
    p1.stop();
    p2.stop();
})

